-- tele.chat — истории V115
-- Выполни файл целиком в Supabase → SQL Editor → New query → Run.

begin;

create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  author_nick text not null references public.users(nick) on update cascade on delete cascade,
  media_type text not null check (media_type in ('image','video')),
  media_url text not null,
  caption text not null default '',
  created_at bigint not null default ((extract(epoch from clock_timestamp()) * 1000)::bigint),
  expires_at bigint not null,
  constraint stories_caption_length_check check (char_length(caption) <= 180),
  constraint stories_media_url_length_check check (char_length(media_url) <= 2048)
);

create table if not exists public.story_views (
  story_id bigint not null references public.stories(id) on delete cascade,
  viewer_nick text not null references public.users(nick) on update cascade on delete cascade,
  viewed_at bigint not null default ((extract(epoch from clock_timestamp()) * 1000)::bigint),
  primary key (story_id, viewer_nick)
);

create index if not exists stories_active_idx on public.stories(expires_at desc, created_at desc);
create index if not exists stories_author_idx on public.stories(author_nick, created_at desc);
create index if not exists story_views_story_idx on public.story_views(story_id, viewed_at desc);

alter table public.stories enable row level security;
alter table public.story_views enable row level security;

drop policy if exists "telechat stories read" on public.stories;
drop policy if exists "telechat stories create" on public.stories;
drop policy if exists "telechat stories delete" on public.stories;
create policy "telechat stories read" on public.stories for select to anon, authenticated using (true);
create policy "telechat stories create" on public.stories for insert to anon, authenticated with check (true);
create policy "telechat stories delete" on public.stories for delete to anon, authenticated using (true);

drop policy if exists "telechat story views read" on public.story_views;
drop policy if exists "telechat story views create" on public.story_views;
create policy "telechat story views read" on public.story_views for select to anon, authenticated using (true);
create policy "telechat story views create" on public.story_views for insert to anon, authenticated with check (true);
drop policy if exists "telechat story views update" on public.story_views;
create policy "telechat story views update" on public.story_views for update to anon, authenticated using (true) with check (true);

grant select, insert, delete on public.stories to anon, authenticated;
grant select, insert, update on public.story_views to anon, authenticated;
grant usage, select on sequence public.stories_id_seq to anon, authenticated;

-- Public bucket for the media that is displayed in story viewers.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('story-media', 'story-media', true, 52428800, array['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime'])
on conflict (id) do update set public=true, file_size_limit=52428800,
  allowed_mime_types=array['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime'];

drop policy if exists "telechat story media read" on storage.objects;
drop policy if exists "telechat story media insert" on storage.objects;
drop policy if exists "telechat story media delete" on storage.objects;
create policy "telechat story media read" on storage.objects for select to anon, authenticated using (bucket_id='story-media');
create policy "telechat story media insert" on storage.objects for insert to anon, authenticated with check (bucket_id='story-media');
create policy "telechat story media delete" on storage.objects for delete to anon, authenticated using (bucket_id='story-media');

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='stories'
  ) then
    alter publication supabase_realtime add table public.stories;
  end if;
end $$;

commit;
notify pgrst, 'reload schema';
