-- TELECHAT GROUP VOICE CALLS V32
-- Run this entire file once in the Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.telechat_group_calls (
  id uuid primary key default gen_random_uuid(),
  host_nick text not null references public.users(nick) on update cascade on delete cascade,
  origin_peer_nick text not null references public.users(nick) on update cascade on delete cascade,
  status text not null default 'active' check (status in ('active','ended','cancelled')),
  created_at bigint not null default ((extract(epoch from clock_timestamp()) * 1000)::bigint),
  started_at bigint,
  ended_at bigint
);

create table if not exists public.telechat_group_call_members (
  call_id uuid not null references public.telechat_group_calls(id) on delete cascade,
  nick text not null references public.users(nick) on update cascade on delete cascade,
  invited_by text not null references public.users(nick) on update cascade on delete cascade,
  status text not null default 'invited' check (status in ('invited','joined','rejected','left','missed')),
  invited_at bigint not null default ((extract(epoch from clock_timestamp()) * 1000)::bigint),
  joined_at bigint,
  left_at bigint,
  primary key (call_id,nick)
);

create table if not exists public.telechat_group_call_signals (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.telechat_group_calls(id) on delete cascade,
  from_nick text not null references public.users(nick) on update cascade on delete cascade,
  to_nick text not null references public.users(nick) on update cascade on delete cascade,
  kind text not null check (kind in ('offer','answer','candidate')),
  payload jsonb not null,
  created_at bigint not null default ((extract(epoch from clock_timestamp()) * 1000)::bigint),
  constraint telechat_group_signal_different_users check (lower(from_nick) <> lower(to_nick))
);

create index if not exists telechat_group_calls_status_idx
  on public.telechat_group_calls(status,created_at desc);
create index if not exists telechat_group_members_nick_idx
  on public.telechat_group_call_members(nick,status,invited_at desc);
create index if not exists telechat_group_members_call_idx
  on public.telechat_group_call_members(call_id,status);
create index if not exists telechat_group_signals_target_idx
  on public.telechat_group_call_signals(call_id,to_nick,id);

alter table public.telechat_group_calls enable row level security;
alter table public.telechat_group_call_members enable row level security;
alter table public.telechat_group_call_signals enable row level security;

drop policy if exists "group calls read" on public.telechat_group_calls;
drop policy if exists "group calls create" on public.telechat_group_calls;
drop policy if exists "group calls update" on public.telechat_group_calls;
drop policy if exists "group calls delete" on public.telechat_group_calls;
create policy "group calls read" on public.telechat_group_calls for select to anon, authenticated using (true);
create policy "group calls create" on public.telechat_group_calls for insert to anon, authenticated with check (true);
create policy "group calls update" on public.telechat_group_calls for update to anon, authenticated using (true) with check (true);
create policy "group calls delete" on public.telechat_group_calls for delete to anon, authenticated using (true);

drop policy if exists "group call members read" on public.telechat_group_call_members;
drop policy if exists "group call members create" on public.telechat_group_call_members;
drop policy if exists "group call members update" on public.telechat_group_call_members;
drop policy if exists "group call members delete" on public.telechat_group_call_members;
create policy "group call members read" on public.telechat_group_call_members for select to anon, authenticated using (true);
create policy "group call members create" on public.telechat_group_call_members for insert to anon, authenticated with check (true);
create policy "group call members update" on public.telechat_group_call_members for update to anon, authenticated using (true) with check (true);
create policy "group call members delete" on public.telechat_group_call_members for delete to anon, authenticated using (true);

drop policy if exists "group call signals read" on public.telechat_group_call_signals;
drop policy if exists "group call signals create" on public.telechat_group_call_signals;
drop policy if exists "group call signals delete" on public.telechat_group_call_signals;
create policy "group call signals read" on public.telechat_group_call_signals for select to anon, authenticated using (true);
create policy "group call signals create" on public.telechat_group_call_signals for insert to anon, authenticated with check (true);
create policy "group call signals delete" on public.telechat_group_call_signals for delete to anon, authenticated using (true);

grant select,insert,update,delete on public.telechat_group_calls to anon, authenticated;
grant select,insert,update,delete on public.telechat_group_call_members to anon, authenticated;
grant select,insert,delete on public.telechat_group_call_signals to anon, authenticated;
grant usage,select on sequence public.telechat_group_call_signals_id_seq to anon, authenticated;

create or replace function public.telechat_guard_group_member_v32()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  active_count integer;
begin
  if not exists (
    select 1 from public.telechat_group_calls
    where id=new.call_id and status='active'
  ) then
    raise exception 'Звонок уже завершён';
  end if;

  if new.status in ('invited','joined')
     and (tg_op='INSERT' or old.status not in ('invited','joined')) then
    select count(*) into active_count
    from public.telechat_group_call_members
    where call_id=new.call_id
      and status in ('invited','joined')
      and lower(nick)<>lower(new.nick);
    if active_count >= 6 then
      raise exception 'В звонке может быть не больше 6 участников';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists telechat_guard_group_member_v32 on public.telechat_group_call_members;
create trigger telechat_guard_group_member_v32
before insert or update on public.telechat_group_call_members
for each row execute function public.telechat_guard_group_member_v32();

create or replace function public.telechat_guard_group_signal_v32()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.telechat_group_calls
    where id=new.call_id and status='active'
  ) then
    raise exception 'Звонок уже завершён';
  end if;
  if not exists (
    select 1 from public.telechat_group_call_members
    where call_id=new.call_id and lower(nick)=lower(new.from_nick) and status='joined'
  ) then
    raise exception 'Отправитель не участвует в звонке';
  end if;
  if not exists (
    select 1 from public.telechat_group_call_members
    where call_id=new.call_id and lower(nick)=lower(new.to_nick) and status in ('invited','joined')
  ) then
    raise exception 'Получатель не участвует в звонке';
  end if;
  return new;
end;
$$;

drop trigger if exists telechat_guard_group_signal_v32 on public.telechat_group_call_signals;
create trigger telechat_guard_group_signal_v32
before insert on public.telechat_group_call_signals
for each row execute function public.telechat_guard_group_signal_v32();

revoke all on function public.telechat_guard_group_member_v32() from public;
revoke all on function public.telechat_guard_group_signal_v32() from public;

do $$
begin
  alter publication supabase_realtime add table public.telechat_group_calls;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.telechat_group_call_members;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.telechat_group_call_signals;
exception when duplicate_object then null;
end $$;

notify pgrst, 'reload schema';
