-- TELECHAT VOICE CALLS V31
-- Run this entire file once in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.telechat_calls (
  id uuid primary key default gen_random_uuid(),
  caller_nick text not null references public.users(nick) on update cascade on delete cascade,
  callee_nick text not null references public.users(nick) on update cascade on delete cascade,
  status text not null default 'ringing' check (status in ('ringing','accepted','ended','rejected','missed','cancelled','busy','failed')),
  offer jsonb,
  answer jsonb,
  created_at bigint not null default ((extract(epoch from clock_timestamp()) * 1000)::bigint),
  updated_at bigint not null default ((extract(epoch from clock_timestamp()) * 1000)::bigint),
  accepted_at bigint,
  ended_at bigint,
  constraint telechat_calls_different_users check (lower(caller_nick) <> lower(callee_nick))
);

create table if not exists public.telechat_call_candidates (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.telechat_calls(id) on delete cascade,
  owner_nick text not null references public.users(nick) on update cascade on delete cascade,
  candidate jsonb not null,
  created_at bigint not null default ((extract(epoch from clock_timestamp()) * 1000)::bigint)
);

create index if not exists telechat_calls_callee_status_idx on public.telechat_calls(callee_nick,status,created_at desc);
create index if not exists telechat_calls_caller_status_idx on public.telechat_calls(caller_nick,status,created_at desc);
create index if not exists telechat_call_candidates_call_idx on public.telechat_call_candidates(call_id,created_at);

alter table public.telechat_calls enable row level security;
alter table public.telechat_call_candidates enable row level security;

drop policy if exists "telechat calls read" on public.telechat_calls;
drop policy if exists "telechat calls create" on public.telechat_calls;
drop policy if exists "telechat calls update" on public.telechat_calls;
drop policy if exists "telechat calls delete" on public.telechat_calls;
create policy "telechat calls read" on public.telechat_calls for select to anon, authenticated using (true);
create policy "telechat calls create" on public.telechat_calls for insert to anon, authenticated with check (true);
create policy "telechat calls update" on public.telechat_calls for update to anon, authenticated using (true) with check (true);
create policy "telechat calls delete" on public.telechat_calls for delete to anon, authenticated using (true);

drop policy if exists "telechat candidates read" on public.telechat_call_candidates;
drop policy if exists "telechat candidates create" on public.telechat_call_candidates;
drop policy if exists "telechat candidates delete" on public.telechat_call_candidates;
create policy "telechat candidates read" on public.telechat_call_candidates for select to anon, authenticated using (true);
create policy "telechat candidates create" on public.telechat_call_candidates for insert to anon, authenticated with check (true);
create policy "telechat candidates delete" on public.telechat_call_candidates for delete to anon, authenticated using (true);

grant select,insert,update,delete on public.telechat_calls to anon, authenticated;
grant select,insert,delete on public.telechat_call_candidates to anon, authenticated;
grant usage,select on sequence public.telechat_call_candidates_id_seq to anon, authenticated;

create or replace function public.telechat_guard_call_v31()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user public.users%rowtype;
  v_now bigint := (extract(epoch from clock_timestamp()) * 1000)::bigint;
begin
  select * into v_user from public.users where lower(nick)=lower(new.caller_nick);
  if v_user.nick is null then raise exception 'Пользователь не найден'; end if;
  if coalesce(v_user.banned_forever,false) or coalesce(v_user.banned_until,0)>v_now then
    raise exception 'Аккаунт заблокирован';
  end if;
  if coalesce(v_user.muted_forever,false) or coalesce(v_user.muted_until,0)>v_now then
    raise exception 'Пользователь находится в муте';
  end if;
  if not exists(select 1 from public.users where lower(nick)=lower(new.callee_nick)) then
    raise exception 'Собеседник не найден';
  end if;
  if exists(
    select 1 from public.telechat_calls c
    where c.status in ('ringing','accepted')
      and c.created_at > v_now - 7200000
      and (lower(c.caller_nick) in (lower(new.caller_nick),lower(new.callee_nick))
        or lower(c.callee_nick) in (lower(new.caller_nick),lower(new.callee_nick)))
  ) then
    raise exception 'Один из пользователей уже разговаривает';
  end if;
  new.created_at := coalesce(new.created_at,v_now);
  new.updated_at := v_now;
  return new;
end;
$$;

drop trigger if exists telechat_guard_call_v31 on public.telechat_calls;
create trigger telechat_guard_call_v31
before insert on public.telechat_calls
for each row execute function public.telechat_guard_call_v31();

revoke all on function public.telechat_guard_call_v31() from public;

do $$
begin
  alter publication supabase_realtime add table public.telechat_calls;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.telechat_call_candidates;
exception when duplicate_object then null;
end $$;

notify pgrst, 'reload schema';
