-- tele.chat — Луны и подарки v20
-- Запусти файл целиком один раз в Supabase SQL Editor.
-- Реальных платежей нет. Creator имеет безлимитный баланс в интерфейсе и RPC.

alter table public.users add column if not exists moons bigint not null default 50;
update public.users set moons = 50 where moons is null;
update public.users set moons = greatest(moons, 1000000000) where lower(nick) = 'creator';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'telechat_users_moons_nonnegative'
      and conrelid = 'public.users'::regclass
  ) then
    alter table public.users
      add constraint telechat_users_moons_nonnegative check (moons >= 0);
  end if;
end $$;

create table if not exists public.moon_gifts (
  id text primary key,
  name text not null,
  icon text not null,
  price bigint not null check (price > 0),
  rarity text not null default 'common',
  theme text not null default 'violet',
  limited boolean not null default false,
  available_until bigint,
  sort_order integer not null default 0
);

create table if not exists public.user_gifts (
  id bigint generated by default as identity primary key,
  owner_nick text not null,
  sender_nick text not null,
  gift_id text not null references public.moon_gifts(id),
  gift_name text not null,
  gift_icon text not null,
  price bigint not null,
  rarity text not null,
  theme text not null,
  limited boolean not null default false,
  message text not null default '',
  created_at bigint not null
);

create table if not exists public.moon_transactions (
  id bigint generated by default as identity primary key,
  from_nick text not null,
  to_nick text not null,
  amount bigint not null check (amount > 0),
  kind text not null check (kind in ('transfer','gift','creator_grant','creator_take')),
  gift_id text,
  note text not null default '',
  created_at bigint not null
);

create index if not exists user_gifts_owner_created_idx on public.user_gifts(owner_nick, created_at desc);
create index if not exists user_gifts_sender_limited_idx on public.user_gifts(sender_nick, limited, created_at desc);
create index if not exists moon_transactions_from_idx on public.moon_transactions(from_nick, created_at desc);
create index if not exists moon_transactions_to_idx on public.moon_transactions(to_nick, created_at desc);

-- 25 обычных подарков + 12 лимитированных. Лимитированная коллекция открыта 42 дня.
insert into public.moon_gifts(id,name,icon,price,rarity,theme,limited,available_until,sort_order) values
('spark_seed','Искра пути','✦',15,'common','violet',false,null,1),
('comet_drop','Капля кометы','☄️',20,'common','blue',false,null,2),
('tiny_orbit','Карманная орбита','🪐',25,'common','indigo',false,null,3),
('crystal_dust','Кристальная пыль','💠',35,'common','cyan',false,null,4),
('nova_heart','Сердце новы','💜',50,'common','rose',false,null,5),
('star_compass','Звёздный компас','🧭',75,'rare','amber',false,null,6),
('dream_capsule','Капсула сна','🫧',100,'rare','cyan',false,null,7),
('cosmic_flower','Цветок космоса','🌺',120,'rare','rose',false,null,8),
('night_lantern','Ночной фонарь','🏮',180,'rare','amber',false,null,9),
('pixel_moon','Пиксельная луна','🌙',250,'rare','violet',false,null,10),
('galaxy_cup','Кубок галактики','🏆',350,'rare','amber',false,null,11),
('stellar_key','Ключ созвездий','🗝️',500,'epic','blue',false,null,12),
('meteor_skate','Метеор-доска','🛹',750,'epic','red',false,null,13),
('orbit_crown','Корона орбиты','👑',1000,'epic','amber',false,null,14),
('lunar_cat','Лунный кот','🐈',1000,'epic','violet',false,null,15),
('nebula_fox','Лис туманности','🦊',1250,'epic','orange',false,null,16),
('space_whale','Кит пустоты','🐋',1800,'epic','cyan',false,null,17),
('astro_radio','Радио дальних миров','📻',2500,'epic','green',false,null,18),
('solar_dragon','Солнечный дракон','🐉',4000,'mythic','orange',false,null,19),
('gravity_cube','Куб гравитации','🎲',6500,'mythic','indigo',false,null,20),
('moon_castle','Замок на Луне','🏰',9000,'mythic','blue',false,null,21),
('time_relic','Реликвия времени','⏳',15000,'mythic','amber',false,null,22),
('void_guitar','Гитара пустоты','🎸',25000,'mythic','red',false,null,23),
('universe_seed','Семя вселенной','🌱',50000,'mythic','green',false,null,24),
('eternal_eclipse','Вечное затмение','🌑',100000,'mythic','black',false,null,25),
('aurora_core','Ядро Авроры','🔮',333,'limited','violet',true,((extract(epoch from clock_timestamp())*1000)::bigint + 3628800000),101),
('red_eclipse','Алое затмение','🌘',777,'limited','red',true,((extract(epoch from clock_timestamp())*1000)::bigint + 3628800000),102),
('celestial_mask','Маска небожителя','🎭',1111,'limited','rose',true,((extract(epoch from clock_timestamp())*1000)::bigint + 3628800000),103),
('chrono_moon','Хронолуна','⌛',2222,'limited','amber',true,((extract(epoch from clock_timestamp())*1000)::bigint + 3628800000),104),
('phoenix_orbit','Орбита Феникса','🪶',5000,'limited','orange',true,((extract(epoch from clock_timestamp())*1000)::bigint + 3628800000),105),
('quantum_crown','Квантовая корона','♛',7500,'limited','blue',true,((extract(epoch from clock_timestamp())*1000)::bigint + 3628800000),106),
('singularity_eye','Око сингулярности','👁️',12000,'limited','black',true,((extract(epoch from clock_timestamp())*1000)::bigint + 3628800000),107),
('frozen_supernova','Замёрзшая сверхновая','❄️',18000,'limited','cyan',true,((extract(epoch from clock_timestamp())*1000)::bigint + 3628800000),108),
('black_comet','Чёрная комета','🖤',25000,'limited','black',true,((extract(epoch from clock_timestamp())*1000)::bigint + 3628800000),109),
('royal_satellite','Королевский спутник','🛰️',50000,'limited','indigo',true,((extract(epoch from clock_timestamp())*1000)::bigint + 3628800000),110),
('dream_portal','Портал сновидений','🌀',75000,'limited','violet',true,((extract(epoch from clock_timestamp())*1000)::bigint + 3628800000),111),
('first_moon','Первая Луна','🌕',150000,'limited','amber',true,((extract(epoch from clock_timestamp())*1000)::bigint + 3628800000),112)
on conflict (id) do update set
  name=excluded.name, icon=excluded.icon, price=excluded.price, rarity=excluded.rarity,
  theme=excluded.theme, limited=excluded.limited, sort_order=excluded.sort_order,
  available_until=case
    when public.moon_gifts.limited and coalesce(public.moon_gifts.available_until,0) < (extract(epoch from clock_timestamp())*1000)::bigint
      then excluded.available_until
    else public.moon_gifts.available_until
  end;

alter table public.moon_gifts enable row level security;
alter table public.user_gifts enable row level security;
alter table public.moon_transactions enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='moon_gifts' and policyname='moon gifts public read') then
    create policy "moon gifts public read" on public.moon_gifts for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='user_gifts' and policyname='user gifts public read') then
    create policy "user gifts public read" on public.user_gifts for select to anon, authenticated using (true);
  end if;
end $$;

grant select on public.moon_gifts, public.user_gifts to anon, authenticated;
revoke insert, update, delete on public.moon_gifts, public.user_gifts, public.moon_transactions from anon, authenticated;

-- Не даём клиенту менять баланс обычным update users.
create or replace function public.telechat_guard_moons()
returns trigger language plpgsql set search_path=public as $$
begin
  if new.moons is distinct from old.moons
     and coalesce(current_setting('telechat.moon_write',true),'') <> 'allowed' then
    raise exception 'Баланс Лун изменяется только через серверную функцию';
  end if;
  return new;
end;
$$;

drop trigger if exists telechat_guard_users_moons on public.users;
create trigger telechat_guard_users_moons
before update of moons on public.users
for each row execute function public.telechat_guard_moons();

create or replace function public.telechat_transfer_moons(
  p_actor_nick text, p_target_nick text, p_amount bigint, p_note text default ''
)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_actor text:=lower(trim(coalesce(p_actor_nick,'')));
  v_target text:=lower(trim(coalesce(p_target_nick,'')));
  v_balance bigint; v_target_exists boolean; v_now bigint:=(extract(epoch from clock_timestamp())*1000)::bigint;
begin
  if p_amount is null or p_amount<1 or p_amount>1000000000 then raise exception 'Некорректная сумма'; end if;
  if v_actor=v_target then raise exception 'Нельзя перевести Луны самому себе'; end if;
  select moons into v_balance from public.users where lower(nick)=v_actor for update;
  select exists(select 1 from public.users where lower(nick)=v_target) into v_target_exists;
  if v_balance is null then raise exception 'Отправитель не найден'; end if;
  if not v_target_exists then raise exception 'Получатель не найден'; end if;
  perform set_config('telechat.moon_write','allowed',true);
  if v_actor<>'creator' then
    update public.users set moons=moons-p_amount where lower(nick)=v_actor and moons>=p_amount returning moons into v_balance;
    if not found then raise exception 'Недостаточно Лун'; end if;
  end if;
  update public.users set moons=moons+p_amount where lower(nick)=v_target;
  insert into public.moon_transactions(from_nick,to_nick,amount,kind,note,created_at)
  values(v_actor,v_target,p_amount,'transfer',left(coalesce(p_note,''),120),v_now);
  return jsonb_build_object('ok',true,'balance',case when v_actor='creator' then 1000000000 else v_balance end,'amount',p_amount,'target',v_target);
end;
$$;

create or replace function public.telechat_send_gift(
  p_actor_nick text, p_target_nick text, p_gift_id text, p_message text default ''
)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_actor text:=lower(trim(coalesce(p_actor_nick,'')));
  v_target text:=lower(trim(coalesce(p_target_nick,'')));
  v_gift public.moon_gifts%rowtype; v_balance bigint; v_target_exists boolean;
  v_now bigint:=(extract(epoch from clock_timestamp())*1000)::bigint;
  v_last_limited bigint; v_record_id bigint;
begin
  select * into v_gift from public.moon_gifts where id=p_gift_id;
  if v_gift.id is null then raise exception 'Подарок не найден'; end if;
  if v_gift.limited and coalesce(v_gift.available_until,0)<=v_now then raise exception 'Лимитированная коллекция уже закрыта'; end if;
  select moons into v_balance from public.users where lower(nick)=v_actor for update;
  select exists(select 1 from public.users where lower(nick)=v_target) into v_target_exists;
  if v_balance is null then raise exception 'Отправитель не найден'; end if;
  if not v_target_exists then raise exception 'Получатель не найден'; end if;
  if v_gift.limited then
    select max(created_at) into v_last_limited from public.user_gifts where lower(sender_nick)=v_actor and limited=true;
    if coalesce(v_last_limited,0)>v_now-1814400000 then
      raise exception 'Лимитированный подарок доступен один раз в 21 день';
    end if;
  end if;
  perform set_config('telechat.moon_write','allowed',true);
  if v_actor<>'creator' then
    update public.users set moons=moons-v_gift.price where lower(nick)=v_actor and moons>=v_gift.price returning moons into v_balance;
    if not found then raise exception 'Недостаточно Лун'; end if;
  end if;
  insert into public.user_gifts(owner_nick,sender_nick,gift_id,gift_name,gift_icon,price,rarity,theme,limited,message,created_at)
  values(v_target,v_actor,v_gift.id,v_gift.name,v_gift.icon,v_gift.price,v_gift.rarity,v_gift.theme,v_gift.limited,left(coalesce(p_message,''),120),v_now)
  returning id into v_record_id;
  insert into public.moon_transactions(from_nick,to_nick,amount,kind,gift_id,note,created_at)
  values(v_actor,v_target,v_gift.price,'gift',v_gift.id,left(coalesce(p_message,''),120),v_now);
  return jsonb_build_object('ok',true,'balance',case when v_actor='creator' then 1000000000 else v_balance end,'gift_record_id',v_record_id,'gift_id',v_gift.id,'limited',v_gift.limited,'next_limited_at',case when v_gift.limited then v_now+1814400000 else null end);
end;
$$;

create or replace function public.telechat_creator_moons(
  p_actor_nick text, p_target_nick text, p_amount bigint, p_note text default ''
)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_actor text:=lower(trim(coalesce(p_actor_nick,'')));
  v_target text:=lower(trim(coalesce(p_target_nick,'')));
  v_balance bigint; v_now bigint:=(extract(epoch from clock_timestamp())*1000)::bigint;
begin
  if v_actor<>'creator' then raise exception 'Только creator может управлять балансом'; end if;
  if v_target='creator' then raise exception 'У creator безлимитный баланс'; end if;
  if p_amount is null or p_amount=0 or abs(p_amount)>1000000000 then raise exception 'Некорректная сумма'; end if;
  perform set_config('telechat.moon_write','allowed',true);
  update public.users set moons=moons+p_amount where lower(nick)=v_target and moons+p_amount>=0 returning moons into v_balance;
  if not found then raise exception 'Пользователь не найден или баланс станет отрицательным'; end if;
  insert into public.moon_transactions(from_nick,to_nick,amount,kind,note,created_at)
  values(v_actor,v_target,abs(p_amount),case when p_amount>0 then 'creator_grant' else 'creator_take' end,left(coalesce(p_note,''),120),v_now);
  return jsonb_build_object('ok',true,'balance',v_balance,'target',v_target);
end;
$$;

create or replace function public.telechat_moon_history(p_nick text,p_limit integer default 50)
returns table(id bigint,from_nick text,to_nick text,amount bigint,kind text,gift_id text,note text,created_at bigint)
language sql security definer set search_path=public as $$
  select t.id,t.from_nick,t.to_nick,t.amount,t.kind,t.gift_id,t.note,t.created_at
  from public.moon_transactions t
  where lower(t.from_nick)=lower(p_nick) or lower(t.to_nick)=lower(p_nick)
  order by t.created_at desc
  limit least(greatest(coalesce(p_limit,50),1),100);
$$;

revoke all on function public.telechat_transfer_moons(text,text,bigint,text) from public;
revoke all on function public.telechat_send_gift(text,text,text,text) from public;
revoke all on function public.telechat_creator_moons(text,text,bigint,text) from public;
revoke all on function public.telechat_moon_history(text,integer) from public;
grant execute on function public.telechat_transfer_moons(text,text,bigint,text) to anon, authenticated;
grant execute on function public.telechat_send_gift(text,text,text,text) to anon, authenticated;
grant execute on function public.telechat_creator_moons(text,text,bigint,text) to anon, authenticated;
grant execute on function public.telechat_moon_history(text,integer) to anon, authenticated;

do $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='user_gifts') then
    alter publication supabase_realtime add table public.user_gifts;
  end if;
end $$;

notify pgrst, 'reload schema';

-- Готово: существующие и новые аккаунты получают 50 Лун, creator отображается как ∞.
