-- tele.chat: лёгкая система модерации v19
-- Запусти файл целиком один раз в Supabase SQL Editor.
-- ВАЖНО: проект пока использует собственный вход по нику/паролю, а не Supabase Auth.
-- Поэтому это базовая защита для небольшого проекта, а не защита от прямых API-запросов.

alter table public.users add column if not exists role text not null default 'user';
alter table public.users add column if not exists verified boolean not null default false;
alter table public.users add column if not exists muted_until bigint;
alter table public.users add column if not exists muted_forever boolean not null default false;
alter table public.users add column if not exists banned_until bigint;
alter table public.users add column if not exists banned_forever boolean not null default false;
alter table public.users add column if not exists moderation_reason text not null default '';
alter table public.users add column if not exists session_version integer not null default 0;

update public.users
set role = 'creator', verified = true
where lower(nick) = 'creator';

update public.users
set role = 'user'
where role not in ('user', 'admin', 'creator');

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'telechat_users_role_check'
      and conrelid = 'public.users'::regclass
  ) then
    alter table public.users
      add constraint telechat_users_role_check
      check (role in ('user', 'admin', 'creator'));
  end if;
end $$;

create table if not exists public.moderation_logs (
  id bigint generated by default as identity primary key,
  actor_nick text not null,
  target_nick text not null,
  action text not null,
  duration_minutes integer,
  reason text not null default '',
  created_at bigint not null default ((extract(epoch from clock_timestamp()) * 1000)::bigint)
);

alter table public.moderation_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'moderation_logs'
      and policyname = 'telechat moderation logs read'
  ) then
    create policy "telechat moderation logs read"
      on public.moderation_logs for select
      to anon, authenticated
      using (true);
  end if;
end $$;

grant select on public.moderation_logs to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

create or replace function public.telechat_moderate(
  p_actor_nick text,
  p_target_nick text,
  p_action text,
  p_minutes integer default null,
  p_reason text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor text := lower(trim(coalesce(p_actor_nick, '')));
  v_target text := lower(trim(coalesce(p_target_nick, '')));
  v_action text := lower(trim(coalesce(p_action, '')));
  v_actor_role text;
  v_target_role text;
  v_now bigint := (extract(epoch from clock_timestamp()) * 1000)::bigint;
  v_until bigint;
  v_result public.users%rowtype;
begin
  select role into v_actor_role from public.users where lower(nick) = v_actor;
  select role into v_target_role from public.users where lower(nick) = v_target;

  if v_actor_role not in ('creator', 'admin') then
    raise exception 'Недостаточно прав';
  end if;
  if v_target_role is null then
    raise exception 'Пользователь не найден';
  end if;
  if v_target = v_actor or v_target = 'creator' or v_target_role = 'creator' then
    raise exception 'Создателя модерировать нельзя';
  end if;

  if v_actor_role = 'admin' then
    if v_target_role <> 'user' then
      raise exception 'Администратор не может модерировать другого администратора';
    end if;
    if v_action not in ('mute', 'unmute', 'ban', 'unban') then
      raise exception 'Администратору доступен только мут и бан';
    end if;
    if v_action in ('mute', 'ban') and (p_minutes is null or p_minutes < 1 or p_minutes > 30) then
      raise exception 'Администратор может выбрать от 1 до 30 минут';
    end if;
  end if;

  if v_action in ('mute', 'ban') and p_minutes is not null then
    if p_minutes < 1 or p_minutes > 5256000 then
      raise exception 'Некорректное время';
    end if;
    v_until := v_now + (p_minutes::bigint * 60000);
  end if;

  case v_action
    when 'mute' then
      update public.users
      set muted_forever = (p_minutes is null),
          muted_until = case when p_minutes is null then null else v_until end,
          moderation_reason = left(coalesce(p_reason, ''), 180)
      where lower(nick) = v_target;
    when 'unmute' then
      update public.users
      set muted_forever = false, muted_until = null, moderation_reason = ''
      where lower(nick) = v_target;
    when 'ban' then
      update public.users
      set banned_forever = (p_minutes is null),
          banned_until = case when p_minutes is null then null else v_until end,
          moderation_reason = left(coalesce(p_reason, ''), 180),
          session_version = session_version + 1
      where lower(nick) = v_target;
    when 'unban' then
      update public.users
      set banned_forever = false, banned_until = null, moderation_reason = ''
      where lower(nick) = v_target;
    when 'kick' then
      update public.users
      set session_version = session_version + 1,
          moderation_reason = left(coalesce(p_reason, ''), 180)
      where lower(nick) = v_target;
    when 'verify' then
      update public.users set verified = true where lower(nick) = v_target;
    when 'unverify' then
      update public.users set verified = false where lower(nick) = v_target;
    when 'make_admin' then
      update public.users set role = 'admin' where lower(nick) = v_target;
    when 'remove_admin' then
      update public.users set role = 'user' where lower(nick) = v_target;
    else
      raise exception 'Неизвестное действие';
  end case;

  insert into public.moderation_logs(actor_nick, target_nick, action, duration_minutes, reason, created_at)
  values (v_actor, v_target, v_action, p_minutes, left(coalesce(p_reason, ''), 180), v_now);

  select * into v_result from public.users where lower(nick) = v_target;
  return jsonb_build_object(
    'ok', true,
    'nick', v_result.nick,
    'role', v_result.role,
    'verified', v_result.verified,
    'muted_until', v_result.muted_until,
    'muted_forever', v_result.muted_forever,
    'banned_until', v_result.banned_until,
    'banned_forever', v_result.banned_forever,
    'session_version', v_result.session_version,
    'moderation_reason', v_result.moderation_reason
  );
end;
$$;

revoke all on function public.telechat_moderate(text, text, text, integer, text) from public;
grant execute on function public.telechat_moderate(text, text, text, integer, text) to anon, authenticated;

-- Лёгкая серверная блокировка сообщений и опросов для пользователей в муте/бане.
create or replace function public.telechat_guard_posting()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nick text;
  v_user public.users%rowtype;
  v_now bigint := (extract(epoch from clock_timestamp()) * 1000)::bigint;
begin
  v_nick := lower(case when tg_table_name = 'polls' then new.created_by else new.from_nick end);
  select * into v_user from public.users where lower(nick) = v_nick;

  if v_user.nick is null then
    raise exception 'Пользователь не найден';
  end if;
  if v_user.banned_forever or coalesce(v_user.banned_until, 0) > v_now then
    raise exception 'Аккаунт заблокирован';
  end if;
  if v_user.muted_forever or coalesce(v_user.muted_until, 0) > v_now then
    raise exception 'Пользователь находится в муте';
  end if;
  return new;
end;
$$;

drop trigger if exists telechat_guard_messages on public.messages;
create trigger telechat_guard_messages
before insert on public.messages
for each row execute function public.telechat_guard_posting();

drop trigger if exists telechat_guard_polls on public.polls;
create trigger telechat_guard_polls
before insert on public.polls
for each row execute function public.telechat_guard_posting();

notify pgrst, 'reload schema';

-- Готово. Аккаунт creator назначен создателем и подтверждён.
