-- tele.chat v3: группы и каналы
-- Выполнить целиком в Supabase → SQL Editor → New query → Run

create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('group','channel')),
  name text not null check (char_length(name) between 2 and 48),
  description text not null default '',
  icon text not null default '🌌',
  owner_nick text not null,
  created_at bigint not null
);

create table if not exists public.room_members (
  room_id bigint not null references public.rooms(id) on delete cascade,
  user_nick text not null,
  role text not null default 'member' check (role in ('owner','admin','member')),
  joined_at bigint not null,
  primary key (room_id,user_nick)
);

create index if not exists room_members_user_nick_idx on public.room_members(user_nick);
create index if not exists rooms_owner_nick_idx on public.rooms(owner_nick);

alter table public.rooms enable row level security;
alter table public.room_members enable row level security;

drop policy if exists "telechat rooms access" on public.rooms;
create policy "telechat rooms access"
on public.rooms for all to anon
using (true) with check (true);

drop policy if exists "telechat room members access" on public.room_members;
create policy "telechat room members access"
on public.room_members for all to anon
using (true) with check (true);

grant select,insert,update,delete on public.rooms to anon;
grant select,insert,update,delete on public.room_members to anon;
grant usage,select on sequence public.rooms_id_seq to anon;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='rooms'
  ) then
    alter publication supabase_realtime add table public.rooms;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='room_members'
  ) then
    alter publication supabase_realtime add table public.room_members;
  end if;
end $$;