const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage();
 await page.route('https://clock.test/**',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><button id="interaction">Interact</button>'}));await page.goto('https://clock.test');
 await page.evaluate(()=>{window.clock=0;window.timers=[];window.calls=[];window.me={nick:'clock',pass:'fixture'};window.player={track:{id:'a'},paused:false,time:0};
 Object.defineProperty(performance,'now',{value:()=>clock});Date.now=()=>1800000000000+clock;
 window.setInterval=(fn,ms)=>{timers.push({fn,ms});return timers.length};window.setTimeout=()=>0;
 window.telechatMusicV96={getState:()=>({...player,track:{...player.track}})};
 window.sb={rpc:async(name,args)=>{calls.push(structuredClone(args.p_data));return {data:{xp:0,level:1,active_seconds:0,music_seconds:0}};}};
 });
 await page.addScriptTag({content:read('activity-model-v124.js')});await page.addScriptTag({content:read('activity-stats-v124.js')});await page.evaluate(()=>telechatActivityV124.sync(true));
 const tick=async(seconds=5,advance=seconds)=>page.evaluate(async({seconds,advance})=>{clock+=seconds*1000;player.time+=advance;timers.find(t=>t.ms===5000).fn();await Promise.resolve();await Promise.resolve();},{seconds,advance});
 for(let i=0;i<24;i++)await tick();await page.evaluate(()=>telechatActivityV124.sync(true));
 let counts=await page.evaluate(()=>calls.reduce((s,p)=>({active:s.active+p.active,music:s.music+p.music}),{active:0,music:0}));
 assert.equal(counts.active,85,'idle tab stops earning activity after 90 seconds');assert.equal(counts.music,115,'real playback continues while idle');
 await page.click('#interaction');await tick();await page.evaluate(()=>telechatActivityV124.sync(true));
 counts=await page.evaluate(()=>calls.reduce((s,p)=>({active:s.active+p.active,music:s.music+p.music}),{active:0,music:0}));assert.equal(counts.active,90,'real interaction restarts activity');
 await page.evaluate(()=>dispatchEvent(new CustomEvent('telechat-native-visibility',{detail:{background:true}})));
 const before=counts;await tick();await page.evaluate(()=>telechatActivityV124.sync(true));counts=await page.evaluate(()=>calls.reduce((s,p)=>({active:s.active+p.active,music:s.music+p.music}),{active:0,music:0}));assert.equal(counts.active,before.active,'background app earns no activity');
 await tick();await page.evaluate(()=>telechatActivityV124.sync(true));let last=await page.evaluate(()=>calls.at(-1));assert.equal(last.music,5,'genuine background playback earns listening');
 await tick(5,100);await page.evaluate(()=>telechatActivityV124.sync(true));last=await page.evaluate(()=>calls.at(-1));assert.equal(last.music,0,'seeking earns no XP');
 await page.evaluate(()=>player.paused=true);await tick();await page.evaluate(()=>telechatActivityV124.sync(true));assert.equal(await page.evaluate(()=>calls.at(-1).music),0,'pause earns no listening');
 const requestCount=await page.evaluate(()=>calls.length);for(let i=0;i<12;i++)await tick();assert.equal(await page.evaluate(()=>calls.length),requestCount,'inactive background does not send empty heartbeats');
 await page.evaluate(()=>player.paused=false);await tick(600,600);await page.evaluate(()=>telechatActivityV124.sync(true));assert.equal(await page.evaluate(()=>calls.at(-1).music),0,'suspension cannot become 10 minutes of listening');
 console.log('PASS activity clock: genuine playback, idle cutoff, real interaction, background, seek, pause, sleep, idle request suppression');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
