const path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');const root=path.resolve(__dirname,'..');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const pages=[];for(const nick of ['alice','bob']){const p=await b.newPage();await p.route('https://rtc.test/**',r=>r.fulfill({body:'<html></html>',contentType:'text/html'}));await p.goto('https://rtc.test/');await p.setContent('<div id="voice-call-overlay"><section class="voice-call-surface"><div class="voice-call-controls"><div class="voice-call-control-wrap"></div></div></section></div>');await p.evaluate(nick=>{window.me={nick};window.remote=nick==='alice'?'bob':'alice';window.state={id:'call-fixture',peers:new Map(),members:new Map([[nick,{nick,status:'joined'}],[remote,{nick:remote,status:'joined'}]])};window.telechatCallsV32={snapshot:()=>state?{id:state.id,status:'active',members:[...state.members.values()]}:null,sendText:text=>telechatCallChatV152.send(state,text)};window.closeCallSheetsV32=()=>telechatCallChatV152.closePanel();window.pc=new RTCPeerConnection({iceServers:[]});window.peer={nick:remote,pc};state.peers.set(remote,peer);},nick);await p.addScriptTag({path:path.join(root,'call-chat-v152.js')});await p.evaluate(nick=>telechatCallChatV152.attach(state,peer,nick==='alice',()=>!!state),nick);pages.push(p);}
 const [a,c]=pages;const offer=await a.evaluate(async()=>{await pc.setLocalDescription(await pc.createOffer());await new Promise(resolve=>{if(pc.iceGatheringState==='complete')return resolve();pc.onicegatheringstatechange=()=>{if(pc.iceGatheringState==='complete')resolve();};});return pc.localDescription.toJSON();});const answer=await c.evaluate(async offer=>{await pc.setRemoteDescription(offer);await pc.setLocalDescription(await pc.createAnswer());await new Promise(resolve=>{if(pc.iceGatheringState==='complete')return resolve();pc.onicegatheringstatechange=()=>{if(pc.iceGatheringState==='complete')resolve();};});return pc.localDescription.toJSON();},offer);await a.evaluate(answer=>pc.setRemoteDescription(answer),answer);await Promise.all(pages.map(p=>p.waitForFunction(()=>peer.chatReadyV152)));
 assert.equal(await a.evaluate(()=>telechatCallsV32.sendText('Привет из звонка').sent),1);await c.waitForFunction(()=>document.getElementById('call-message-toast-v152').textContent.includes('Привет из звонка'));assert(await c.locator('#call-message-toast-v152').isVisible());await c.waitForFunction(()=>document.getElementById('call-message-toast-v152').hidden,null,{timeout:5500});
 await c.evaluate(()=>telechatCallsV32.sendText('<img src=x>'));await a.waitForFunction(()=>document.getElementById('call-message-toast-v152').textContent.includes('<img src=x>'));assert.equal(await a.locator('#call-message-toast-v152 img').count(),0);
 await a.locator('#call-chat-btn-v152').click();assert.equal(await a.locator('.call-chat-message-v152').count(),2);await a.evaluate(()=>{peer.chatChannelV152.send('{bad json');peer.chatChannelV152.send(JSON.stringify({v:1,id:'valid-long-id',text:'x'.repeat(1601)}));});await c.waitForTimeout(80);assert.equal(await c.locator('.call-chat-message-v152').count(),2);
 await a.evaluate(()=>{window.backup=state;state=null;dispatchEvent(new CustomEvent('telechat-call-ui-v152'));});assert.equal(await a.locator('.call-chat-message-v152').count(),0);assert(await a.locator('#call-message-toast-v152').evaluate(e=>e.hidden));await Promise.all(pages.map(p=>p.evaluate(()=>pc.close())));
 console.log('PASS real WebRTC: bidirectional call text, capability handshake, 4-second popup, retained in-call log, invalid payload bounds, XSS safety and cleanup');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
