const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const p=await browser.newPage({viewport:{width:1100,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.setContent('<div id="active-chat"><header>Чат</header><div id="messages"></div><footer>Сообщение</footer></div>');await p.addStyleTag({content:'#active-chat{margin-left:240px;width:600px;height:650px;display:flex;flex-direction:column;transform:translate3d(0,0,0);background:#171525;color:white}header,footer{height:70px;flex:none}#messages{flex:1;min-height:0;overflow:auto}.msg{height:100px;flex:none;border-bottom:1px solid #444}'+read('chat-scroll-v132.css')});await p.evaluate(()=>{window.currentChat='';window.conversationKey=()=>currentChat;window.openChat=async nick=>{currentChat=nick;document.querySelector('#active-chat').style.display='flex';const box=document.querySelector('#messages');box.innerHTML=Array.from({length:25},(_,i)=>'<div class="msg">'+nick+' '+i+'</div>').join('');scrollToBottom();await new Promise(r=>setTimeout(r,90));};window.openRoom=room=>openChat(room.id);window.goBack=()=>{currentChat='';document.querySelector('#active-chat').style.display='none';};});await p.addScriptTag({content:read('chat-scroll-v132.js')});
 const gap=()=>p.evaluate(()=>{const b=document.querySelector('#messages');return b.scrollHeight-b.scrollTop-b.clientHeight;});
 await p.evaluate(()=>openChat('alice'));await p.waitForTimeout(60);assert(await gap()<3,'opens at latest message');
 await p.waitForTimeout(250);await p.evaluate(()=>document.querySelector('.msg').style.height='900px');await p.waitForTimeout(90);assert(await gap()<3,'late media bigger than old 180px threshold stays at bottom');
 await p.locator('#messages').hover();await p.mouse.wheel(0,-700);await p.waitForTimeout(150);assert(await gap()>150);assert(await p.getByRole('button',{name:'К последним сообщениям'}).isVisible());const top=await p.locator('#messages').evaluate(b=>b.scrollTop);await p.evaluate(()=>document.querySelector('.msg').style.height='1100px');await p.waitForTimeout(100);assert.equal(await p.locator('#messages').evaluate(b=>b.scrollTop),top,'reading history is not pulled down by image load');
 const br=await p.locator('.chat-bottom-v132').boundingBox(),mr=await p.locator('#messages').boundingBox();assert(br.x>=mr.x&&br.x+br.width<=mr.x+mr.width&&br.y+br.height<=mr.y+mr.height,'button is in message viewport even with transformed chat');await p.getByRole('button',{name:'К последним сообщениям'}).click();await p.waitForTimeout(100);assert(await gap()<3);assert.equal(await p.locator('.chat-bottom-v132').isVisible(),false);
 await p.evaluate(()=>{const b=document.querySelector('#messages');b.scrollTop=600;});await p.waitForTimeout(30);await p.evaluate(()=>openChat('alice'));await p.waitForTimeout(60);assert(await gap()<3,'reopening same chat goes to end');
 await p.evaluate(()=>{window.pending=openChat('bob');document.querySelector('#messages').dispatchEvent(new WheelEvent('wheel',{deltaY:-400}));document.querySelector('#messages').scrollTop=400;});await p.waitForTimeout(180);assert.equal(await p.locator('#messages').evaluate(b=>b.scrollTop),400,'manual scroll during open wins');
 await p.evaluate(()=>openRoom({id:'group'}));await p.waitForTimeout(70);assert(await gap()<3,'group opening goes to end');await p.evaluate(()=>document.querySelector('footer').style.height='150px');await p.waitForTimeout(80);assert(await gap()<3,'composer growth keeps end visible');
 await p.evaluate(()=>{void openChat('old');goBack();});await p.waitForTimeout(200);assert.equal(await p.locator('.chat-bottom-v132').isVisible(),false,'late open completion cannot revive closed chat');
 for(const width of [390,320]){await p.setViewportSize({width,height:700});await p.addStyleTag({content:'#active-chat{margin:0;width:100%;height:650px}'});await p.evaluate(()=>openChat('phone'));await p.waitForTimeout(70);assert(await gap()<3);await p.locator('#messages').evaluate(b=>b.scrollTop=100);await p.waitForTimeout(50);const r=await p.locator('.chat-bottom-v132').boundingBox();assert(r.x>=0&&r.x+r.width<=width);}
 assert.deepEqual(errors,[]);console.log('PASS scroll: chat/group/same-chat opening, late media, user history preserved, bottom button, transformed container, composer resize, cancelled opening, 320/390 mobile');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
