const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 await context.addInitScript(()=>{window.me={nick:'wallpaper-tester'};window.doLogin=async()=>true;});
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,tag=>/chat-wallpaper-v119.js|appearance-mode-v95.js/.test(tag)?tag:'');
 await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname!=='telechat.test')return r.abort();if(u.pathname==='/')return r.fulfill({contentType:'text/html',body:html});const file=path.join(root,decodeURIComponent(u.pathname));if(!fs.existsSync(file))return r.abort();return r.fulfill({contentType:file.endsWith('.css')?'text/css':'application/javascript',body:fs.readFileSync(file)});});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 async function ready(){await page.goto('https://telechat.test/');await page.evaluate(()=>{document.querySelector('#startup-loader')?.remove();document.querySelector('#auth-screen').classList.remove('active');document.querySelector('#chat-screen').classList.add('active');document.querySelector('#settings-panel').classList.add('open','v65-full-panel');document.querySelector('#settings-panel').style.cssText='display:block;visibility:visible;transform:none;right:0;z-index:1000';document.querySelector('#active-chat').style.display='flex';document.querySelector('#empty-state').style.display='none';document.querySelector('#contacts-list').innerHTML='<div class="list-section-title">Личные чаты</div><div class="contact"><div class="av">☽</div><div class="contact-info"><div class="contact-name">Друг</div><div class="contact-last">Проверка читаемости фотофона</div></div></div>';document.querySelector('#messages').innerHTML='<div class="msg them"><div class="msg-bubble">Привет! Вот как смотрится фотофон.</div><div class="msg-time">12:20</div></div><div class="msg me"><div class="msg-bubble">У каждого раздела может быть своё фото</div><div class="msg-time">12:21</div></div>';});await page.waitForSelector('#wallpaper-settings-v119');}
 await ready();
 const png=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=2400;c.height=1400;const g=c.getContext('2d');const gradient=g.createLinearGradient(0,0,c.width,c.height);gradient.addColorStop(0,'#7259a5');gradient.addColorStop(.5,'#164763');gradient.addColorStop(1,'#132933');g.fillStyle=gradient;g.fillRect(0,0,c.width,c.height);g.fillStyle='#ffd49c';g.beginPath();g.arc(1800,300,150,0,7);g.fill();return c.toDataURL('image/png').split(',')[1];}),'base64');
 const upload=page.locator('#wallpaper-file-v119');
 await upload.setInputFiles({name:'фон.png',mimeType:'image/png',buffer:png});await page.waitForSelector('#messages.has-wallpaper-v119');assert.equal(await page.locator('#contacts-list').getAttribute('class'),'contacts-list');assert.match(await page.locator('#messages').evaluate(e=>getComputedStyle(e).backgroundImage),/blob:/);
 await page.locator('label:has(input[name=wallpaper-target-v119][value=list])').click();await upload.setInputFiles({name:'список.png',mimeType:'image/png',buffer:png});await page.waitForSelector('#contacts-list.has-wallpaper-v119');const before=await page.locator('#messages').evaluate(e=>e.style.getPropertyValue('--wallpaper-photo-v119'));await page.locator('#wallpaper-shade-v119').evaluate(e=>{e.value='65';e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));});await page.waitForFunction(()=>document.querySelector('#wallpaper-status-v119').textContent.includes('сохранено'));assert.equal(await page.locator('#messages').evaluate(e=>e.style.getPropertyValue('--wallpaper-photo-v119')),before,'Other background untouched');
 await page.screenshot({path:path.join(root,'outputs/wallpapers-v119-desktop.png')});
 await ready();await page.waitForSelector('#messages.has-wallpaper-v119');await page.waitForSelector('#contacts-list.has-wallpaper-v119');assert.equal(await page.locator('#contacts-list').evaluate(e=>e.style.getPropertyValue('--wallpaper-shade-v119')),'0.65','Background and dim level persist after reload');
 await page.locator('label:has(input[name=wallpaper-target-v119][value=list])').click();await page.locator('#wallpaper-remove-v119').click();await page.waitForFunction(()=>!document.querySelector('#contacts-list').classList.contains('has-wallpaper-v119'));assert.equal(await page.locator('#messages').evaluate(e=>e.classList.contains('has-wallpaper-v119')),true);
 await upload.setInputFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('not an image')});await page.waitForFunction(()=>document.querySelector('#wallpaper-status-v119').classList.contains('is-error'));assert.equal(await page.locator('#contacts-list').evaluate(e=>e.classList.contains('has-wallpaper-v119')),false,'Failed decode does not replace background');
 await page.locator('label:has(input[name=wallpaper-target-v119][value=both])').click();await upload.setInputFiles({name:'both.png',mimeType:'image/png',buffer:png});await page.waitForSelector('#contacts-list.has-wallpaper-v119');
 for(const width of [390,320]){await page.setViewportSize({width,height:844});await page.locator('#wallpaper-settings-v119').scrollIntoViewIfNeeded();assert.equal(await page.locator('#wallpaper-settings-v119').evaluate(e=>e.scrollWidth>e.clientWidth+1),false,'No settings overflow '+width);assert.match(await page.locator('#messages').evaluate(e=>getComputedStyle(e).backgroundImage),/blob:/,'Works with phone calm mode');if(width===390)await page.screenshot({path:path.join(root,'outputs/wallpapers-v119-phone.png')});}
 await page.evaluate(async()=>{me={nick:'other-user'};await doLogin();});await page.waitForFunction(()=>!document.querySelector('#messages').classList.contains('has-wallpaper-v119'));assert.equal(await page.locator('#contacts-list').evaluate(e=>e.classList.contains('has-wallpaper-v119')),false,'Different account does not inherit wallpaper');
 await page.evaluate(async()=>{me={nick:'wallpaper-tester'};await doLogin();});await page.waitForSelector('#contacts-list.has-wallpaper-v119');await page.locator('#wallpaper-remove-v119').click();await page.waitForFunction(()=>!document.querySelector('#messages').classList.contains('has-wallpaper-v119'));await ready();assert.equal(await page.locator('#messages').evaluate(e=>e.classList.contains('has-wallpaper-v119')),false,'Removal persists');
 assert.deepEqual(errors,[]);console.log('PASS wallpaper: separate targets, both targets, reload persistence, dim level, corrupt image, removal, account isolation, 320/390 mobile, no page errors.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
