const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname!=='design.test')return route.abort();const file=path.join(root,u.pathname==='/'?'index.html':u.pathname.slice(1));if(!fs.existsSync(file))return route.fulfill({status:404,body:''});let body=fs.readFileSync(file);if(file.endsWith('.html'))body=body.toString('utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');return route.fulfill({body,contentType:file.endsWith('.css')?'text/css':'text/html; charset=utf-8'});});
 await page.goto('https://design.test/');await page.addScriptTag({path:path.join(root,'conversation-design-v150.js')});
 await page.evaluate(()=>{
  document.getElementById('startup-loader')?.remove();document.getElementById('auth-screen').classList.remove('active');document.getElementById('chat-screen').classList.add('active');document.getElementById('active-chat').style.display='flex';document.getElementById('no-chat')?.remove();document.getElementById('empty-state').style.display='none';document.querySelector('.chat-name').textContent='Алиса';document.querySelector('.chat-status-text')?.replaceChildren(document.createTextNode('в сети'));
  const avatar='<svg viewBox="0 0 48 48" width="46" height="46"><rect width="48" height="48" rx="24" fill="#9080bd"/><circle cx="24" cy="18" r="8" fill="#ece6fc"/><path d="M9 45v-4a15 15 0 0 1 30 0v4" fill="#ece6fc"/></svg>';
  const contacts=document.getElementById('contacts-list');contacts.innerHTML='<div class="list-section-title">Личные чаты</div>';
  for(const [i,name,last] of [[0,'Алиса','Давай послушаем вместе'],[1,'Максим','Фотографии с выходных'],[2,'Данил','Ты уже дома?'],[3,'Саша','До завтра!'],[4,'Команда tele.chat','Новая версия готова']]){const row=document.createElement('div');row.className='contact'+(i===0?' active':i===2?' has-unread-v62':'');row.innerHTML='<div class="av">'+avatar+'</div><div class="contact-info"><div class="contact-name">'+name+'</div><div class="contact-last">'+last+'</div></div><div class="contact-time">14:32'+(i===2?'<span class="chat-unread-v62">2</span>':'')+'</div>';contacts.append(row);}
  const box=document.getElementById('messages');box.replaceChildren();const date=document.createElement('div');date.className='date-divider';date.textContent='Сегодня';box.append(date);window.base=new Date(2026,9,4,14,30).getTime();window.messageRows=[];
  window.addMessage=(nick,text,offset,extra={})=>{const row=document.createElement('div');row.className='msg '+(nick==='me'?'me':'them');row.dataset.id=String(messageRows.length+1);row._messageSourceV136={from_nick:nick,chat_key:'alice_me',ts:base+offset,text,...extra};row.innerHTML=(nick==='me'?'':'<div class="msg-sender-name">'+(nick==='alice'?'Алиса':'Максим')+'</div>')+(extra.reply_text?'<div class="msg-reply-ref">Ответ на сообщение</div>':'')+'<div class="msg-bubble"></div><div class="msg-meta"><span class="msg-time">'+new Date(base+offset).toTimeString().slice(0,5)+'</span>'+(nick==='me'?'<span class="msg-check read">✓✓</span>':'')+'</div>';row.querySelector('.msg-bubble').textContent=text;box.append(row);messageRows.push(row);return row;};
  addMessage('alice','Привет! Как проходит выходной?',0);addMessage('alice','Нашла несколько новых треков',12000);addMessage('alice','Давай послушаем вместе',22000);
  addMessage('me','Привет, давай!',35000);addMessage('me','Сейчас создам комнату',42000);addMessage('alice','Отлично, жду приглашение',65000);
  telechatMessageLayoutV150.sync(box);
 });
 assert.equal(await page.locator('.flow-joined-v150').count(),3);assert.equal(await page.locator('.flow-time-shared-v150').count(),3);
 assert.equal(await page.locator('.msg').nth(1).locator('.msg-sender-name').isVisible(),false);assert.equal(await page.locator('.msg').nth(0).locator('.msg-sender-name').isVisible(),true);
 // Identical repaint does not mutate rows or re-create their contents.
 assert.equal(await page.evaluate(()=>{const box=document.getElementById('messages'),observer=new MutationObserver(()=>{});observer.observe(box,{subtree:true,attributes:true,childList:true});const old=messageRows[0].querySelector('.msg-bubble');telechatMessageLayoutV150.sync(box);const count=observer.takeRecords().length;observer.disconnect();return count+(old!==messageRows[0].querySelector('.msg-bubble')?100:0);}),0);
 await page.evaluate(()=>{addMessage('alice','Ответ остаётся отдельным',80000,{reply_text:'вопрос'});addMessage('alice','Через некоторое время',500000);telechatMessageLayoutV150.sync(document.getElementById('messages'));});assert.equal(await page.locator('.msg').nth(6).evaluate(e=>e.classList.contains('flow-joined-v150')),false);assert.equal(await page.locator('.msg').nth(7).evaluate(e=>e.classList.contains('flow-joined-v150')),false);
 for(const light of [false,true])for(const width of [390,1440]){
  await page.setViewportSize({width,height:900});await page.evaluate(({light,width})=>{document.body.classList.toggle('theme-light',light);document.body.classList.toggle('telechat-mobile-v100',width<720);document.getElementById('chat-screen').classList.toggle('chat-open',width<720);}, {light,width});
  assert.equal(await page.locator('.contact').nth(1).evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');assert.notEqual(await page.locator('.contact.active').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');
  assert.equal(await page.locator('.msg').nth(1).locator('.msg-bubble').evaluate(e=>getComputedStyle(e).borderTopLeftRadius),'6px');
  assert(await page.locator('#messages').evaluate(e=>e.scrollWidth<=e.clientWidth+1));assert.equal(await page.locator('.msg-check').count(),2);
  if(width<720){await page.screenshot({path:path.join(root,`outputs/conversation-list-v150-${light?'light':'dark'}-${width}.png`)});await page.evaluate(()=>{document.querySelector('.sidebar').classList.add('hidden');document.querySelector('.chat-main').classList.add('visible');});}
  await page.waitForFunction(()=>{const r=document.getElementById('messages').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1;});
  const rect=await page.locator('#messages').boundingBox();assert(rect&&rect.width>200&&rect.x>=0&&rect.x+rect.width<=width+1,'Messages must be on-screen: '+JSON.stringify({width,light,rect}));
  await page.screenshot({path:path.join(root,`outputs/conversation-v150-${light?'light':'dark'}-${width}.png`)});
  if(width<720)await page.evaluate(()=>{document.querySelector('.sidebar').classList.remove('hidden');document.querySelector('.chat-main').classList.remove('visible');});
 }
 await page.evaluate(()=>{document.getElementById('messages').classList.add('has-wallpaper-v119');document.getElementById('messages').style.setProperty('--wallpaper-photo-v119','linear-gradient(45deg,#344355,#788aa4)');});assert((await page.locator('#messages').evaluate(e=>getComputedStyle(e).backgroundImage)).includes('52, 67, 85'));
 // A removed message must not leave stale grouping on its neighbour.
 await page.evaluate(()=>{messageRows[1].remove();messageRows[0].remove();telechatMessageLayoutV150.sync(document.getElementById('messages'));});assert.equal(await page.locator('.msg').first().locator('.msg-sender-name').isVisible(),true);
 assert.deepEqual(errors,[]);console.log('PASS v150: grouping, same-minute timestamps, author/reply/time boundaries, no-op paint stability, deletion, dark/light desktop/mobile, flat list, receipts and wallpaper preservation');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
