const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');

const html=read('index.html');
const css=read('emoji-motion-v80.css');
const js=read('emoji-motion-v80.js');
const worker=read('sw.js');
const activity=read('android-app/app/src/main/java/chat/tele/app/MainActivity.java');
const gradle=read('android-app/app/build.gradle');
const workflow=read('.github/workflows/build-android-apk.yml');

assert.match(html,/emoji-motion-v80\.css\?v=82/);
assert.match(html,/emoji-motion-v80\.js\?v=82/);
assert.ok(html.indexOf('emoji-motion-v80.css?v=82')>html.indexOf('mobile-experience-v79.css?v=79'));
assert.ok(html.indexOf('emoji-motion-v80.js?v=82')>html.indexOf('mobile-experience-v79.js?v=79'));
assert.match(css,/grid-template-columns:repeat\(auto-fill,42px\)/);
assert.match(css,/\.chat-more-v52\.v80-motion-ready\{scale:1!important/);
assert.doesNotMatch(css,/button\.v80-motion-ready\{[^}]*position:relative/);
assert.doesNotMatch(css,/button\.v80-motion-ready\{[^}]*transition:transform/);
assert.doesNotMatch(css,/v80-button-ripple/);
assert.match(css,/emoji-grid-v80/);
assert.match(js,/const CATEGORIES=/);
assert.match(js,/\(min-width:721px\) and \(pointer:fine\)/);
assert.match(js,/if\(!desktopQuery\.matches\)return/);
assert.match(js,/MutationObserver/);
assert.match(js,/const releaseButton=/);
assert.doesNotMatch(js,/v80-button-ripple/);
assert.match(js,/setRangeText/);
assert.match(js,/telechat-emoji-recent-v80/);
assert.ok((js.match(/id:'/g)||[]).length>=11,'expected at least 11 emoji categories');
assert.ok((js.match(/[\u{1F300}-\u{1FAFF}]/gu)||[]).length>=500,'expected a large emoji library');
assert.match(worker,/telechat-shell-v97-music-card/);
assert.match(activity,/\?app=android&v=85/);
assert.match(activity,/telechat-android\/1\.2\.2/);
assert.match(gradle,/versionCode 5/);
assert.match(gradle,/versionName '1\.2\.2'/);
assert.match(workflow,/tele\.chat-Android-1\.2\.2\.apk/);

console.log('emoji motion V80 smoke: ok');
