const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1200,height:850}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.abort());
 let html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');html=html.replace(/<link\b[^>]*href="([^"?]+)[^"]*"[^>]*>/gi,(tag,file)=>file.endsWith('.css')?'<style>'+fs.readFileSync(path.join(root,file),'utf8')+'</style>':'');await page.setContent(html);
 await page.evaluate(()=>{
  window.me={nick:'creator',name:'creator',pass:'fixture-only'};window.store=new Map();window.calls=[];window.fail=false;window.delayedRead=false;
  document.getElementById('startup-loader')?.remove();document.getElementById('auth-screen').classList.remove('active');document.getElementById('chat-screen').classList.add('active');
  const nav=document.querySelector('[data-nav="profile"]');document.body.append(nav);Object.assign(nav.style,{position:'fixed',bottom:'14px',left:'20px',width:'64px',height:'56px',zIndex:'100'});
  window.telechatNavigate=()=>{};window.unpackProfileData=()=>({});window.setAvatarElement=node=>node.textContent='C';window.applyProfileBanner=node=>node.style.background='linear-gradient(135deg,#655078,#35304c)';
  window.sb={from(table){let nick;const q={select(){return q;},eq(k,v){nick=v;return q;},maybeSingle(){return q;},abortSignal(){return q;},then(resolve){calls.push({type:'read',nick,table});const snapshot=store.get(nick)||null;return new Promise(done=>{const finish=()=>done({data:snapshot,error:fail?{message:'offline'}:null});if(delayedRead)window.finishRead=finish;else finish();}).then(resolve);}};return q;},rpc(name,args){calls.push({type:'write',name,args});return {abortSignal(){return fail?Promise.resolve({error:{message:'offline'}}):new Promise(resolve=>{const result={nick:args.p_nick,kind:args.p_kind,title:args.p_title};store.set(args.p_nick,result);resolve({data:result});});}};}};
 });
 for(const file of ['profile-quick-v91.js','game-status-catalog-v151.js','game-status-v151.js'])await page.addScriptTag({path:path.join(root,file)});
 const trigger=page.locator('[data-nav="profile"]');await trigger.click();await page.locator('[data-pq="game"]').click();assert(await page.locator('#game-status-v151').isVisible());assert(!(await page.locator('#profile-quick-v91').isVisible()));
 const count=await page.evaluate(()=>({games:telechatGameCatalogV151.filter(x=>x.kind==='game').length,apps:telechatGameCatalogV151.filter(x=>x.kind==='app').length}));assert(count.games>400&&count.apps>100);console.log('Catalogue:',count);
 assert.equal(await page.locator('.gs-option').count(),60,'Bound rendered list size');await page.locator('.gs-search input').fill('minecraft');assert.equal(await page.locator('.gs-option').count(),1);await page.locator('.gs-option').click();assert(!(await page.locator('#game-status-v151').isVisible()));assert.equal(await page.evaluate(()=>telechatGameStatusV151.get('creator').title),'Minecraft');
 await trigger.click();assert.equal(await page.locator('[data-pq="game"] span').textContent(),'Изменить игровой статус');await page.locator('[data-pq="game"]').click();assert((await page.locator('.gs-current').textContent()).includes('Играет в Minecraft'));
 await page.locator('[data-filter="app"]').click();await page.locator('.gs-search input').fill('blender');await page.locator('.gs-option').click();assert.equal(await page.evaluate(()=>telechatGameStatusV151.get('creator').kind),'app');
 // Cross-account view reads only the small public status, never profile photos/passwords.
 await page.evaluate(async()=>{me={nick:'observer',pass:'fixture'};await telechatGameStatusV151.refresh('creator',true);});assert.equal(await page.evaluate(()=>telechatGameStatusV151.get('creator').title),'Blender');await page.evaluate(()=>me={nick:'creator',pass:'fixture-only'});
 await page.evaluate(()=>telechatGameStatusV151.open());await page.locator('.gs-clear').click();assert.equal(await page.evaluate(()=>telechatGameStatusV151.get('creator')),null);
 await page.evaluate(()=>telechatGameStatusV151.open());await page.locator('.gs-search input').fill('<img src=x onerror=alert(1)>');assert.equal(await page.locator('.gs-custom img').count(),0);await page.locator('[data-custom="game"]').click();assert.equal(await page.evaluate(()=>telechatGameStatusV151.get('creator').title),'<img src=x onerror=alert(1)>');
 await page.evaluate(()=>telechatGameStatusV151.open());await page.locator('.gs-search input').fill('Minecraft');await page.evaluate(()=>fail=true);await page.locator('.gs-option').click();assert(await page.locator('#game-status-v151').isVisible());assert((await page.locator('.gs-error').textContent()).includes('Не удалось'));assert.equal(await page.locator('.gs-option').isEnabled(),true);await page.evaluate(()=>fail=false);
 // A late SELECT cannot overwrite a just-saved choice.
 await page.evaluate(()=>{delayedRead=true;telechatGameStatusV151.refresh('creator',true);});await page.waitForFunction(()=>!!window.finishRead);await page.locator('.gs-option').click();await page.evaluate(()=>{delayedRead=false;finishRead();});await page.waitForTimeout(30);assert.equal(await page.evaluate(()=>telechatGameStatusV151.get('creator').title),'Minecraft');
 await page.evaluate(()=>telechatGameStatusV151.open());await page.locator('.gs-search input').fill('Моя очень длинная игра '.repeat(3));
 for(const light of [false,true])for(const width of [320,390,1200]){await page.setViewportSize({width,height:740});await page.evaluate(light=>document.body.classList.toggle('theme-light',light),light);const r=await page.locator('#game-status-v151').boundingBox();assert(r.x>=0&&r.y>=0&&r.x+r.width<=width+1&&r.y+r.height<=741);assert(await page.locator('#game-status-v151').evaluate(e=>e.scrollWidth<=e.clientWidth));await page.screenshot({path:path.join(root,`outputs/game-status-v151-${light?'light':'dark'}-${width}.png`)});}
 await page.keyboard.press('Escape');assert(!(await page.locator('#game-status-v151').isVisible()));
 const writes=await page.evaluate(()=>calls.filter(x=>x.type==='write'));assert(writes.every(x=>x.args.p_nick==='creator'));assert.deepEqual(errors,[]);console.log('PASS game status: picker, search/filter, save/clear, cross-account read, safe custom title, network failure, stale read race, dark/light 320/390/1200, keyboard close');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
