const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage();
 await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname!=='light.test')return route.abort();const f=path.join(root,u.pathname==='/'?'index.html':u.pathname.slice(1));if(!fs.existsSync(f))return route.fulfill({status:404,body:''});let body=fs.readFileSync(f,'utf8');if(f.endsWith('.html'))body=body.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');return route.fulfill({body,contentType:f.endsWith('.css')?'text/css':'text/html'});});await page.goto('https://light.test/');
 await page.evaluate(()=>{document.querySelector('#startup-loader')?.remove();document.querySelector('#auth-screen').classList.remove('active');document.body.classList.add('theme-light');document.querySelector('#chat-screen').classList.add('active');document.querySelector('#active-chat').style.display='flex';document.querySelector('#no-chat')?.remove();document.querySelector('.chat-name').textContent='Друг';document.querySelector('#messages').innerHTML='<div class="msg them"><div class="msg-bubble">Привет! Как тебе новая белая тема?</div><span class="msg-time">12:40</span></div><div class="msg me"><div class="msg-bubble">Теперь всё читается.</div></div>';document.querySelector('#contacts-list').innerHTML='<div class="contact active"><div class="av">A</div><div><div class="contact-name">Алиса</div><div class="contact-last">Слушаем вместе?</div></div></div><div class="contact"><div class="av">Б</div><div><div class="contact-name">Борис</div><div class="contact-last">Привет</div></div></div>';document.querySelector('#msg-input').placeholder='Написать сообщение…';});
 await page.evaluate(()=>document.querySelector('#empty-state').style.display='none');
 for(const width of [390,1440]){await page.setViewportSize({width,height:900});await page.evaluate(w=>{document.body.classList.toggle('telechat-mobile-v100',w<720);document.querySelector('#chat-screen').classList.toggle('chat-open',w<720);},width);await page.waitForTimeout(250);for(const selector of ['.chat-header','#msg-input','#search-inp','.composer-shell','.input-area']){const bg=await page.locator(selector).first().evaluate(e=>getComputedStyle(e).backgroundColor);assert(/^rgb\((?:2[3-5]\d)/.test(bg),selector+' must be light: '+bg);}await page.screenshot({path:path.join(root,`outputs/light-v147-${width}.png`)});}
 await page.evaluate(()=>{for(const id of ['messages','contacts-list']){const e=document.getElementById(id);e.classList.add('has-wallpaper-v119');e.style.setProperty('--wallpaper-photo-v119','linear-gradient(45deg,#344355,#788aa4)');}});
 assert((await page.locator('#contacts-list').evaluate(e=>getComputedStyle(e).backgroundImage)).includes('52, 67, 85'),'Custom wallpaper preserved');assert.equal(await page.locator('.contact-name').first().evaluate(e=>getComputedStyle(e).color),'rgb(37, 43, 62)');
 await page.screenshot({path:path.join(root,'outputs/light-v147-wallpaper.png')});
 await page.evaluate(()=>document.body.classList.remove('theme-light'));assert.notEqual(await page.locator('.chat-header').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 255, 255)','Dark theme unchanged');
 console.log('PASS light theme: real CSS cascade, desktop/mobile composer, custom wallpaper, contacts, theme switch');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
