const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage({viewport:{width:390,height:800},isMobile:true,hasTouch:true});await p.route('**/*',r=>r.fulfill({contentType:'text/html',body:'<meta name="viewport" content="width=device-width,initial-scale=1"><div id="messages"></div><textarea id="msg-input"></textarea>'}));await p.goto('http://telechat.test');await p.evaluate(()=>Object.assign(window,{
 me:{nick:'me'},currentChat:'friend',currentRoom:null,lastRenderedDate:'',userCache:{},serverRows:[],deliveries:[],conversationKey:()=>currentChat?'me_'+currentChat:'',renderMessages:async()=>{},renderContacts:async()=>{},updateStatusBar:async()=>{},markAsRead:async()=>{},avatarMarkup:()=>'',renderPoll:()=>{},scrollToBottom:()=>{},batchUsersV15:async()=>{},isOnline:()=>false,formatLastSeen:()=>'',normalizedRoomVisibility:()=>'',makeDateStr:()=> 'today',pendingMedia:null,replyTo:null,canWriteCurrent:()=>true,cancelReply:()=>{},cancelPendingMedia:()=>{},playSendSound:()=>{},showToast:()=>{},doLogin:async()=>{},sendMsg:async()=>{},
 sb:{from:table=>({insert(row){this.row=row;return this},select(){return this},single(){return new Promise(resolve=>deliveries.push({row:this.row,resolve}));},delete(){return this},eq(){return this},order(){return this},limit(n){this.count=n;return this},lt(f,v){this.before=v;return this},then(resolve,reject){return Promise.resolve({data:table==='messages'?serverRows.filter(r=>!this.before||r.ts<this.before).sort((a,b)=>b.ts-a.ts).slice(0,this.count):[]}).then(resolve,reject)}})},
 appendMessage:async m=>{const row=document.createElement('div');row.className='msg';row.dataset.id=m.id||'';const text=document.createElement('span');text.textContent=m.text;row.append(text);row.insertAdjacentHTML('beforeend','<div class="msg-meta"></div>');document.querySelector('#messages').append(row);}
 }));for(const f of ['chat-reliability-v24.js','chat-speed-v51.js'])await p.addScriptTag({content:read(f)});
 await p.evaluate(async()=>{serverRows=[{id:1,ts:Date.now()+60000,chat_key:conversationKey(),from_nick:'friend',text:'already received'}];await renderMessages();document.querySelector('#msg-input').value='first';await sendMsg();document.querySelector('#msg-input').value='second';await sendMsg();});await p.waitForFunction(()=>deliveries.length===2);assert.deepEqual(await p.locator('.msg>span').allTextContents(),['already received','first','second']);assert(await p.evaluate(()=>deliveries[0].row.ts>serverRows[0].ts&&deliveries[1].row.ts>deliveries[0].row.ts),'phone clock behind received messages does not insert sends above them');
 await p.evaluate(()=>{window.first=document.querySelectorAll('.msg')[1];window.second=document.querySelectorAll('.msg')[2];const d=deliveries[1],saved={...d.row,id:22};serverRows.push(saved);d.resolve({data:saved});});await p.waitForFunction(()=>second.dataset.id==='22');await p.evaluate(()=>{const d=deliveries[0],saved={...d.row,id:99};serverRows.push(saved);d.resolve({data:saved});});await p.waitForFunction(()=>first.dataset.id==='99');await p.evaluate(()=>telechatChatSpeedV51.repaintActive());assert.deepEqual(await p.locator('.msg>span').allTextContents(),['already received','first','second']);assert(await p.evaluate(()=>first===document.querySelectorAll('.msg')[1]&&second===document.querySelectorAll('.msg')[2]),'out-of-order acknowledgement keeps existing row nodes');assert.equal(await p.locator('.msg').count(),3);
 console.log('PASS phone sends: behind-device clock, sequential timestamps, rapid sends, reverse acknowledgement, stable nodes/order, no duplicates');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
