const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..');
const read=name=>fs.readFileSync(path.join(root,name),'utf8');
const html=read('index.html'),style=read('mobile-adaptation-v100.css'),script=read('mobile-optimization-v100.js'),worker=read('sw.js');
assert.match(html,/mobile-adaptation-v100\.css\?v=100/);
assert.match(html,/mobile-optimization-v100\.js\?v=100/);
assert.match(style,/telechat-mobile-v100/);
assert.match(style,/sidebar\.hidden \+ \.chat-main/);
assert.match(style,/profile-panel\.v65-full-panel/);
assert.match(script,/visualViewport/);
assert.match(script,/deviceMemory/);
assert.match(worker,/mobile-adaptation-v100\.css\?v=100/);
assert.match(worker,/mobile-optimization-v100\.js\?v=100/);
console.log('mobile-adaptation-v100 smoke ok');
