const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
function wav(){const b=Buffer.alloc(44+16000*120);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(8000,24);b.writeUInt32LE(16000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(b.length-44,40);return b;}
const mock=()=>{
 window.me={nick:'tester',name:'Тестовый автор',pass:'fixture-only',av:0};window.showToast=t=>window.lastToast=t;
 window.SUPABASE_URL='https://db.test';window.SUPABASE_KEY='fixture';window.avatarMarkup=()=>'<span>◐</span>';
 window.fixture={tracks:Array.from({length:8},(_,i)=>({id:`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`,title:['Ночной город','На своей волне','Тёплый сентябрь','Последний поезд','Тихий океан','Звёзды рядом','После дождя','Дальше'][i],artist:['spacewalk','creator','nocturne','mae'][i%4],author_nick:i===1?'tester':'artist',source:'link',url:'https://audio.test/song.wav?'+i,duration:120,size:0,description:'Музыка для ночных прогулок.',genre:'Электроника',cover_url:'',likes_count:i*3,created_at:new Date(Date.now()-i*1000).toISOString()})),saved:[],liked:[],playlists:[],calls:[],uploads:[]};
 const persisted=localStorage.getItem('fixture_reload_v119');if(persisted)window.fixture=JSON.parse(persisted);
 window.sb={from(table){let eqs=[],ids=null,search='',sort='',range=null,limit=null,single=false;const q={select(){return q},eq(k,v){eqs.push([k,v]);return q},in(k,v){ids=v;return q},order(k){if(!sort)sort=k;return q},or(v){search=v.split('%')[1]||'';return q},range(a,b){range=[a,b];return q},limit(n){limit=n;return q},maybeSingle(){single=true;return q},then(resolve,reject){let rows=table==='users'?[me,{nick:'artist',name:'Автор',av:0}]:fixture.tracks.map(t=>({...t}));rows=rows.filter(t=>eqs.every(([k,v])=>t[k]===v)&&(!ids||ids.includes(table==='users'?t.nick:t.id)));if(search)rows=rows.filter(t=>(t.title+' '+t.artist).toLowerCase().includes(search.toLowerCase()));if(sort==='likes_count')rows.sort((a,b)=>b.likes_count-a.likes_count);if(range)rows=rows.slice(range[0],range[1]+1);if(limit)rows=rows.slice(0,limit);return Promise.resolve({data:single?rows[0]||null:rows,error:null}).then(resolve,reject)}};return q},async rpc(name,args){const {p_action:a,p_data:d}=args;fixture.calls.push({a,d});if(args.p_pass!=='fixture-only')return {error:{message:'Auth required'}};let data={};if(a==='library')data={saved:fixture.saved,liked:fixture.liked,playlists:fixture.playlists};if(a==='like'||a==='save'){const key=a==='like'?'liked':'saved';fixture[key]=d.enabled?[...new Set([...fixture[key],d.track_id])]:fixture[key].filter(id=>id!==d.track_id);}if(a==='upload_ticket')data={id:d.id||crypto.randomUUID(),token:'fixture-upload'};if(a==='publish'){data={...d,author_nick:me.nick,created_at:new Date().toISOString(),likes_count:0};fixture.tracks.unshift(data);fixture.saved.push(data.id);}if(a==='create_playlist'){data={id:crypto.randomUUID(),title:d.title,track_ids:[]};fixture.playlists.push(data);}if(a==='playlist_add'){const p=fixture.playlists.find(p=>p.id===d.playlist_id);if(!p.track_ids.includes(d.track_id))p.track_ids.push(d.track_id);}if(a==='playlist_remove')fixture.playlists.find(p=>p.id===d.playlist_id).track_ids=fixture.playlists.find(p=>p.id===d.playlist_id).track_ids.filter(x=>x!==d.track_id);if(a==='delete_playlist')fixture.playlists=fixture.playlists.filter(p=>p.id!==d.playlist_id);if(a==='delete_track'){fixture.tracks=fixture.tracks.filter(t=>t.id!==d.track_id);fixture.saved=fixture.saved.filter(x=>x!==d.track_id);}return {data:structuredClone(data),error:null}}};
 window.supabase={createClient:()=>({storage:{from:()=>({async upload(p,file){fixture.uploads.push({p,size:file.size});return {data:{},error:null}},getPublicUrl:p=>({data:{publicUrl:'https://db.test/storage/v1/object/public/music-media/'+p}}),async remove(){return {error:null}}})}})};
 window.telechatProfileMusicV97={getOwn:()=>window.profileTrack||null,save:async t=>window.profileTrack=t};
};
const scMock=`(()=>{const events=Object.fromEntries(['READY','ERROR','PLAY','PAUSE','PLAY_PROGRESS','SEEK','FINISH'].map(x=>[x,x]));window.widgets=[];function Widget(frame){const c={};const w={frame,paused:true,plays:0,volume:100,bind(n,fn){c[n]=fn},unbind(n){delete c[n]},emit(n,d){c[n]?.(d)},getCurrentSound(fn){fn({title:'SoundCloud test',duration:180000})},play(){this.paused=false;this.plays++;this.emit('PLAY')},pause(){this.paused=true;this.emit('PAUSE')},seekTo(ms){this.emit('SEEK',{currentPosition:ms})},setVolume(v){this.volume=v}};widgets.push(w);setTimeout(()=>w.emit('READY'),15);return w}Widget.Events=events;window.SC={Widget}})();`;
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addInitScript(mock);
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,tag=>/music-library-v96.js|music-hub-v117.js|soundcloud-v98.js/.test(tag)?tag:'');
 await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname==='audio.test'||u.hostname==='db.test')return r.fulfill({contentType:'audio/wav',body:wav()});if(u.pathname==='/player/api.js')return r.fulfill({contentType:'application/javascript',body:scMock});if(u.hostname==='w.soundcloud.com')return r.fulfill({contentType:'text/html',body:'<body style="background:white;color:black">Official player fixture</body>'});if(u.hostname!=='telechat.test')return r.abort();if(u.pathname==='/')return r.fulfill({contentType:'text/html',body:html});const file=path.join(root,decodeURIComponent(u.pathname));if(!fs.existsSync(file))return r.abort();return r.fulfill({contentType:file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'application/javascript',body:fs.readFileSync(file)});});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('https://telechat.test/');await page.evaluate(()=>{document.querySelector('#startup-loader')?.remove();document.querySelector('#auth-screen')?.classList.remove('active');document.querySelector('#chat-screen')?.classList.add('active');});
 await page.locator('.music-entry-v96').click();await page.waitForSelector('.mh-track');assert.equal(await page.locator('.mh-track').count(),8);assert.equal(await page.locator('#music-dialog-v96').evaluate(e=>e.open),false);
 await page.screenshot({path:path.join(root,'outputs/music-hub-v117-desktop.png')});
 const first=page.locator('.mh-track').first();await first.locator('[data-action=like]').click();await page.waitForFunction(()=>fixture.liked.length===1);await first.locator('[data-action=save]').click();await page.waitForFunction(()=>fixture.saved.length===1);
 await first.locator('[data-action=play]').first().click();await page.waitForFunction(()=>telechatMusicV96.getState().track&&!telechatMusicV96.getState().paused);const trackId=await page.evaluate(()=>telechatMusicV96.getState().track.id);
 await page.waitForFunction(()=>[...document.querySelectorAll('.music-player-v96 [data-music=toggle]')].every(b=>b.dataset.state==='pause'));
 assert.equal(await page.locator(`.mh-release[data-id="${trackId}"] .mh-release-play`).getAttribute('data-mode'),'pause','Release cover follows actual playback');
 await page.locator(`.mh-release[data-id="${trackId}"]`).click();await page.waitForFunction(()=>telechatMusicV96.getState().paused);
 assert.equal(await page.locator(`.mh-release[data-id="${trackId}"] .mh-release-play`).getAttribute('data-mode'),'play');
 await page.locator(`.mh-release[data-id="${trackId}"]`).click();await page.waitForFunction(()=>!telechatMusicV96.getState().paused);
 await page.locator('.mh-back').click();assert.equal(await page.locator('#music-hub-v117').isVisible(),false);assert.equal(await page.evaluate(()=>telechatMusicV96.getState().paused),false,'Closing hub keeps playback');await page.locator('.music-entry-v96').click();await page.waitForSelector('.mh-track');assert.equal(await page.evaluate(()=>telechatMusicV96.getState().track.id),trackId);
 await page.locator('.mh-nav [data-view=library]').click();assert.equal(await page.locator('.mh-track').count(),1);await page.locator('.mh-track [data-action=more]').click();await page.locator('[data-action=to-playlist]').click();await page.locator('[data-action=create-playlist]').click();await page.locator('#mh-playlist-form input').fill('Ночные прогулки');await page.locator('#mh-playlist-form button').click();await page.waitForFunction(()=>fixture.playlists[0]?.track_ids.length===1);await page.waitForSelector('#mh-sheet',{state:'hidden'});assert.match(await page.locator('.mh-page-title h1').textContent(),/Ночные/);
 const uploadsBefore=await page.evaluate(()=>fixture.uploads.length),publicBefore=await page.evaluate(()=>fixture.tracks.length);
 await page.locator('[data-action=playlist-files]').click();await page.locator('[data-action=playlist-import]').click();await page.locator('#mh-local-files').setInputFiles({name:'Моя личная песня.wav',mimeType:'audio/wav',buffer:wav()});
 await page.waitForFunction(()=>document.querySelectorAll('.mh-track').length===2).catch(async e=>{console.log(await page.evaluate(async()=>({notice:document.querySelector('#mh-notice').textContent,status:document.querySelector('#music-status-v96').textContent,tracks:await telechatMusicV96.getTracks(),local:JSON.stringify(localStorage)})));throw e;});const localRow=page.locator('.mh-track').filter({hasText:'Моя личная песня'});
 assert.equal(await page.evaluate(()=>fixture.uploads.length),uploadsBefore,'Private import never uploads');assert.equal(await page.evaluate(()=>fixture.tracks.length),publicBefore,'Private import never publishes');assert.equal(await page.evaluate(()=>fixture.playlists[0].track_ids.length),1,'Local IDs never reach public catalog FK');
 await localRow.locator('[data-action=play]').first().click();await page.waitForFunction(()=>telechatMusicV96.getState().track?.kind==='file'&&!telechatMusicV96.getState().paused);
 assert.equal(await page.locator('.music-sidebar-player [data-music=next]').isDisabled(),false,'Mini player follows mixed playlist queue');
 await localRow.locator('[data-action=more]').click();await page.locator('[data-action=playlist-remove]').click();await page.waitForFunction(()=>document.querySelectorAll('.mh-track').length===1);assert.equal(await page.evaluate(async()=>(await telechatMusicV96.getTracks()).length),1,'Removing playlist membership preserves audio');
 await page.locator('[data-action=playlist-files]').click();await page.locator('.mh-device-tracks [data-action=playlist-add]').click();await page.waitForFunction(()=>document.querySelectorAll('.mh-track').length===2);
 await page.locator('.mh-nav [data-view=playlists]').click();assert.match(await page.locator('.mh-playlist-card small').textContent(),/2 треков/);await page.locator('.mh-playlist-card').click();
 await page.locator('[data-action=playlist-files]').click();await page.locator('.mh-device-tracks [data-action=playlist-add]').click();assert.equal(await page.locator('.mh-track').count(),2,'Duplicate local membership is idempotent');
 await page.locator('[data-action=playlist-files]').click();await page.locator('[data-action=playlist-import]').click();await page.locator('#mh-local-files').setInputFiles({name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('not audio')});await page.waitForFunction(()=>document.querySelector('#mh-notice').textContent.includes('аудио'));assert.equal(await page.locator('.mh-track').count(),2,'Invalid file does not enter playlist');
 for(const width of [320,390]){await page.setViewportSize({width,height:844});assert.equal(await page.locator('#music-hub-v117').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);}
 await page.setViewportSize({width:1440,height:1000});
 await page.locator('.mh-publish-top').click();await page.locator('#mh-publish-form [data-source=link]').click();await page.locator('#mh-publish-form [name=url]').fill('http://audio.test/song.wav');await page.locator('#mh-publish-form [name=title]').fill('Проверка');await page.locator('#mh-publish-form [name=rights]').check();await page.locator('#mh-publish-form [type=submit]').click();await page.waitForFunction(()=>document.querySelector('#mh-publish-status').textContent.includes('HTTPS'));
 await page.locator('#mh-publish-form [name=url]').fill('https://audio.test/publish.wav');await page.locator('#mh-publish-form [name=title]').fill('Мой первый релиз');await page.locator('#mh-publish-form [name=description]').fill('Описание <без HTML>');await page.locator('#mh-publish-form [type=submit]').click();await page.waitForSelector('#mh-sheet',{state:'hidden'});await page.waitForFunction(()=>fixture.tracks.some(t=>t.title==='Мой первый релиз'));assert.match(await page.locator('.mh-profile-identity h1').textContent(),/Тестовый/);
 await page.locator('.mh-publish-top').click();await page.locator('#mh-publish-form input[name=audio]').setInputFiles({name:'offline.wav',mimeType:'audio/wav',buffer:wav()});await page.locator('#mh-publish-form [name=rights]').check();await page.locator('#mh-publish-form [type=submit]').click();await page.waitForSelector('#mh-sheet',{state:'hidden'});assert.equal(await page.evaluate(()=>fixture.uploads.length),1);
 await page.locator('.mh-nav nav [data-view=home]').click();await page.locator('#mh-search').fill('Ночной');await page.waitForFunction(()=>document.querySelectorAll('.mh-track').length===1);assert.match(await page.locator('.mh-track-title').textContent(),/Ночной/);await page.locator('#mh-search').fill('');await page.waitForFunction(()=>document.querySelectorAll('.mh-track').length>=8);
 await page.evaluate(()=>fixture.tracks.unshift({id:'sc-fixture',title:'SoundCloud test',artist:'SoundCloud',author_nick:'artist',url:'https://soundcloud.com/artist/test',duration:180,likes_count:0,created_at:new Date().toISOString()}));await page.locator('[data-filter=popular]').click();await page.waitForSelector('.mh-track[data-track="sc-fixture"]');await page.locator('.mh-track[data-track="sc-fixture"] [data-action=play]').first().click();await page.waitForFunction(()=>window.widgets?.at(-1)?.plays===1);
 assert.equal(await page.locator('#mh-cloud-host iframe').count(),1);assert.match(await page.locator('#mh-cloud-host iframe').evaluate(e=>getComputedStyle(e).filter),/invert/);await page.locator('#mh-sc-dark').uncheck();assert.equal(await page.locator('#mh-cloud-host iframe').evaluate(e=>getComputedStyle(e).filter),'none');await page.locator('.mh-back').click();assert.equal(await page.evaluate(()=>widgets.at(-1).paused),false);await page.locator('.music-entry-v96').click();await page.waitForSelector('.mh-track');
 assert.equal(await page.locator('.music-sidebar-player [data-music=toggle]').getAttribute('data-state'),'pause','SoundCloud mini player shows pause');
 for(const width of [390,320,768,1024]){await page.setViewportSize({width,height:844});await page.waitForTimeout(100);const overflow=await page.locator('#music-hub-v117').evaluate(e=>e.scrollWidth>e.clientWidth+1);assert.equal(overflow,false,'No overflow at '+width);if(width===390){await page.screenshot({path:path.join(root,'outputs/music-hub-v117-phone.png')});await page.locator('.mh-publish-top').click();await page.screenshot({path:path.join(root,'outputs/music-hub-v117-publish-phone.png')});await page.locator('[data-action=sheet-close]').click();}}
 await page.setViewportSize({width:1440,height:1000});await page.locator('.mh-nav [data-view=profile]').click();await page.waitForSelector('.mh-track');const own=page.locator('.mh-track').filter({hasText:'Мой первый релиз'});await own.locator('[data-action=more]').click();await page.locator('[data-action=delete-track]').click();await page.locator('[data-action=confirm-delete]').click();await page.waitForFunction(()=>!fixture.tracks.some(t=>t.title==='Мой первый релиз'));
 await page.evaluate(()=>localStorage.setItem('fixture_reload_v119',JSON.stringify(fixture)));await page.reload();await page.evaluate(()=>{document.querySelector('#startup-loader')?.remove();document.querySelector('#auth-screen').classList.remove('active');document.querySelector('#chat-screen').classList.add('active');});await page.locator('.music-entry-v96').click();await page.waitForSelector('.mh-track');await page.locator('.mh-nav [data-view=playlists]').click();await page.locator('.mh-playlist-card').click();assert.equal(await page.locator('.mh-track').count(),2,'Mixed playlist survives full page reload');
 const restored=page.locator('.mh-track').filter({hasText:'Моя личная песня'});await restored.locator('[data-action=play]').first().click();await page.waitForFunction(()=>telechatMusicV96.getState().track?.kind==='file'&&!telechatMusicV96.getState().paused);await restored.locator('[data-action=more]').click();await page.locator('[data-action=delete-track]').click();await page.locator('[data-action=confirm-delete]').click();await page.waitForFunction(()=>document.querySelectorAll('.mh-track').length===1);assert.equal(await page.evaluate(async()=>(await telechatMusicV96.getTracks()).length),0,'Device deletion clears audio and playlist references');
 assert.deepEqual(errors,[]);console.log('PASS music hub: responsive layouts, release/mini play states, private device files in mixed playlists, persistence/removal, likes/saves, publishing, validation, SoundCloud, deletion; no page errors.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
