const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const context=await browser.newContext();const peers=new Map(),members=new Map();let lastPacket;
 await context.route('https://together.test/**',r=>r.fulfill({contentType:'text/html',body:'<div class="sidebar-top"></div>'}));
 await context.exposeBinding('relay',async({page},data)=>{const topic=data.topic||peers.get(page);if(data.remove){peers.delete(page);members.delete(page);}else peers.set(page,topic);if(data.presence)members.set(page,data.presence);if(data.presence||data.remove){const state=Object.fromEntries([...members].filter(([p])=>peers.get(p)===topic).map(([p,m],i)=>[String(i),[m]]));await Promise.all([...peers].filter(([p,t])=>t===topic).map(([p])=>p.evaluate(s=>window.syncPresence(s),state)));}if(data.message){if(data.message.event==='state')lastPacket=data.message.payload;await Promise.all([...peers].filter(([p,t])=>p!==page&&t===topic).map(([p])=>p.evaluate(m=>window.deliver(m),data.message)));}return 'ok';});
 async function make(nick){const p=await context.newPage();await p.goto('https://together.test/');await p.evaluate(nick=>{
  window.me={nick};window.doLogin=async()=>{};window.player={track:{id:'song',kind:'link',url:'https://audio.test/one.mp3',title:'Один трек',duration:180},time:15,paused:false};window.plays=0;
  window.telechatMusicV96={getState:()=>({...player}),async playTrack(t){player.track=t;player.paused=false;plays++;},async toggle(){player.paused=!player.paused},pause(){player.paused=true},stop(){player.track=null;player.paused=true},seek(t){player.time=t}};
  window.sb={channel(topic){const listeners={};let state={};window.syncPresence=s=>{state=s;listeners.sync?.();};window.deliver=m=>listeners[m.event]?.({payload:m.payload});return {presenceState:()=>state,track:presence=>relay({topic,presence}),on(type,{event},fn){listeners[event]=fn;return this},subscribe(fn){relay({topic}).then(()=>fn('SUBSCRIBED'));return this},send(message){return relay({topic,message})}}},removeChannel(){return relay({remove:true})}};
 },nick);await p.addStyleTag({path:path.join(root,'music-together-v147.css')});await p.addScriptTag({path:path.join(root,'music-together-v147.js')});return p;}
 const host=await make('host'),guest=await make('guest');
 await host.evaluate(()=>telechatTogetherV147.create());const link=await host.evaluate(()=>telechatTogetherV147.state().link);assert(!link.includes('private'));
 await guest.evaluate(link=>telechatTogetherV147.join(link),link);await guest.waitForFunction(()=>player.track?.id.startsWith('together:')&&!player.paused);assert.equal(await guest.evaluate(()=>player.track.title),'Один трек');
 await host.waitForFunction(()=>telechatTogetherV147.state().listeners.length===2);await guest.waitForFunction(()=>document.querySelectorAll('.together-member-v148').length===2);assert.equal(await guest.locator('.together-member-v148').first().locator('strong').textContent(),'host');
 await host.evaluate(()=>{player.paused=true;dispatchEvent(new Event('telechat-music-state-v97'));});await guest.waitForFunction(()=>player.paused);
 await host.evaluate(()=>{player.paused=false;player.time=83;dispatchEvent(new Event('telechat-music-state-v97'));});await guest.waitForFunction(()=>!player.paused&&player.time>=83);
 const malicious={...lastPacket,raw:lastPacket.raw.replace('Один трек','Взломанный трек')};await guest.evaluate(payload=>deliver({event:'state',payload}),malicious);assert.equal(await guest.evaluate(()=>player.track.title),'Один трек');
 await host.evaluate(()=>{player.track={id:'local',kind:'file',title:'Local'};dispatchEvent(new Event('telechat-music-state-v97'));});await guest.waitForFunction(()=>player.paused);
 await host.evaluate(()=>{player.track={id:'song2',kind:'link',url:'https://audio.test/two.mp3',title:'Второй трек'};player.paused=false;player.time=0;dispatchEvent(new Event('telechat-music-state-v97'));});await guest.waitForFunction(()=>player.track.title==='Второй трек'&&!player.paused);
 // Invitations never join or start music until the recipient explicitly clicks Join.
 const friend=await make('newfriend');
 for(const p of [host,friend]){await p.evaluate(()=>{window.renderMessageContent=t=>'plain:'+t;window.messagePreviewText=t=>t;window.userCache={newfriend:{name:'Друг'}};window.sentInvites=[];window.telechatDeliveryV72={sendDirect:async(nick,text,options)=>{sentInvites.push({nick,text,options});return true;}};sb.from=table=>({select:()=>({eq:(field,nick)=>({maybeSingle:async()=>({data:nick==='missing'?null:{nick}})})})});document.body.insertAdjacentHTML('beforeend','<div id="contacts-list"><div data-contact-nick="newfriend"></div></div><div id="fixture-messages"></div>');});await p.addScriptTag({path:path.join(root,'music-room-invites-v148.js')});}
 await host.locator('[data-together="invite"]').click();await host.locator('.together-invite-chat-v148 button').click();await host.waitForFunction(()=>sentInvites.length===1);assert.equal(await host.locator('.together-invite-chat-v148 button').isDisabled(),true);
 const sent=await host.evaluate(()=>sentInvites[0]);assert.equal(sent.nick,'newfriend');assert(sent.options.expiresAt>Date.now());
 await friend.evaluate(text=>{document.getElementById('fixture-messages').innerHTML='<div class="msg them">'+renderMessageContent(text)+'</div>';},sent.text);assert.equal(await friend.evaluate(()=>telechatTogetherV147.state()),null);assert.equal(await friend.evaluate(()=>plays),0);
 await friend.locator('[data-room-invite="ignore"]').click();assert.equal(await friend.evaluate(()=>telechatTogetherV147.state()),null);assert.match(await friend.locator('.room-invite-result-v148').textContent(),/проигнорировано/);
 await friend.evaluate(text=>{document.getElementById('fixture-messages').innerHTML='<div class="msg them">'+renderMessageContent(text)+'</div>';},sent.text);assert.equal(await friend.locator('.room-invite-buttons-v148').isVisible(),false);
 const second=sent.text.replace(/invite=\d+/,`invite=${Date.now()+1}`);await friend.evaluate(text=>{document.getElementById('fixture-messages').innerHTML='<div class="msg them">'+renderMessageContent(text)+'</div>';},second);await friend.locator('[data-room-invite="join"]').click();await friend.waitForFunction(()=>player.track?.title==='Второй трек'&&telechatTogetherV147.state()?.connected);await host.waitForFunction(()=>telechatTogetherV147.state().listeners.length===3);
 await friend.evaluate(()=>telechatTogetherV147.leave());await host.waitForFunction(()=>telechatTogetherV147.state().listeners.length===2);
 await host.locator('.together-invite-form-v148 input').fill('@other');await host.locator('.together-invite-form-v148 button').click();await host.waitForFunction(()=>sentInvites.length===2);assert.equal(await host.evaluate(()=>sentInvites[1].nick),'other');
 await host.locator('.together-invite-form-v148 input').fill('@missing');await host.locator('.together-invite-form-v148 button').click();await host.waitForFunction(()=>document.querySelector('.together-invite-status-v148').textContent.includes('не найден'));assert.equal(await host.evaluate(()=>sentInvites.length),2);
 assert.equal(await friend.evaluate(text=>telechatRoomInvitesV148.parse(text.replace('together.test','evil.test')),sent.text),null);
 const expired=sent.text.replace(/invite=\d+/,`invite=${Date.now()-16*60*1000}`);await friend.evaluate(text=>{document.getElementById('together-v147').close();document.getElementById('fixture-messages').innerHTML='<div class="msg them">'+renderMessageContent(text)+'</div>';},expired);assert.equal(await friend.locator('.room-invite-buttons-v148').isVisible(),false);
 await host.addStyleTag({content:':root{--bg:#11121c;--bg2:#1a1b2a;--bg3:#242538;--text:#eeeaf8;--text2:#a39db7;--accent3:#baa7f5;--border:#ffffff18}body{background:#0f1019;font-family:system-ui}'});await host.screenshot({path:path.join(root,'outputs/room-v148-desktop.png')});await host.setViewportSize({width:320,height:640});assert(await host.locator('#together-v147').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await host.screenshot({path:path.join(root,'outputs/room-v148-mobile.png')});
 await guest.setViewportSize({width:320,height:640});assert(await guest.locator('#together-v147').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await guest.screenshot({path:path.join(root,'outputs/together-v147-320.png')});
 await host.evaluate(()=>telechatTogetherV147.leave(true));await guest.waitForFunction(()=>telechatTogetherV147.state()===null);assert.equal(await guest.evaluate(()=>player.paused),true);
 await assert.rejects(()=>guest.evaluate(()=>telechatTogetherV147.join('https://example.com/#listen=bad')));
 await host.evaluate(()=>{player.track={kind:'file',url:'blob:private',title:'Secret'};});await assert.rejects(()=>host.evaluate(()=>telechatTogetherV147.create()));
 console.log('PASS together: signed sync, presence join/leave, pause/seek/track change, private chat invitations by chat/nick, explicit Join/Ignore, duplicate guard, missing user, expiry, foreign origin rejection, tamper rejection, host close, 320px dialog');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
