const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const context=await browser.newContext({viewport:{width:1366,height:900}});
 await context.addInitScript(()=>{
  window.me={nick:'intro_test',name:'Intro fixture',pass:'fixture'};window.showToast=()=>{};
  window.sb={rpc:async()=>({data:{saved:[],liked:[],playlists:[]},error:null}),from(){const q={select(){return q},in(){return q},eq(){return q},order(){return q},range(){return q},limit(){return q},then(fn){return Promise.resolve({data:[],error:null}).then(fn)}};return q}};
  window.createdAudioContexts=[];const Native=window.AudioContext;window.AudioContext=class extends Native{constructor(...args){super(...args);window.createdAudioContexts.push(this)}};
 });
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,t=>/music-library-v96.js|music-hub-v117.js|music-intro-v118.js|soundcloud-v98.js/.test(t)?t:'');
 await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname!=='telechat.test')return r.abort();if(u.pathname==='/')return r.fulfill({contentType:'text/html',body:html});const f=path.join(root,decodeURIComponent(u.pathname));if(!fs.existsSync(f))return r.abort();return r.fulfill({contentType:f.endsWith('.css')?'text/css':f.endsWith('.png')?'image/png':'application/javascript',body:fs.readFileSync(f)});});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 async function start(){await page.goto('https://telechat.test/');await page.evaluate(()=>{document.querySelector('#startup-loader')?.remove();document.querySelector('#auth-screen')?.classList.remove('active');document.querySelector('#chat-screen')?.classList.add('active');});await page.locator('.music-entry-v96').click();}
 await start();await page.waitForSelector('.mh-intro-v118');assert.equal(await page.locator('#mh-intro-title-v118').innerText(),'Ну что,\nготов попасть\nв мир музыки?');await page.waitForFunction(()=>createdAudioContexts.length===1&&createdAudioContexts[0].state==='running');
 assert.equal(await page.locator('.mh-nav').evaluate(e=>e.inert),true);await page.waitForTimeout(1550);await page.screenshot({path:path.join(root,'outputs/music-intro-v118-desktop.png')});
 await page.waitForSelector('.mh-intro-v118',{state:'detached',timeout:6500});assert.equal(await page.locator('.mh-nav').evaluate(e=>e.inert),false);await page.waitForFunction(()=>createdAudioContexts.every(c=>c.state==='closed'));assert.equal(await page.evaluate(()=>document.activeElement.id),'mh-search');
 await page.locator('.mh-back').click();await page.locator('.music-entry-v96').click();assert.equal(await page.locator('.mh-intro-v118').count(),0,'Welcome shown once per session');
 await start();await page.locator('[data-intro-sound]').click();assert.equal(await page.locator('[data-intro-sound]').getAttribute('aria-pressed'),'false');await page.keyboard.press('Escape');await page.waitForSelector('.mh-intro-v118',{state:'detached'});assert.equal(await page.locator('#music-hub-v117').isVisible(),true,'Escape skips intro, not music');await page.waitForFunction(()=>createdAudioContexts.every(c=>c.state==='closed'));
 await page.setViewportSize({width:390,height:844});await start();await page.waitForTimeout(1450);assert.equal(await page.evaluate(()=>createdAudioContexts.length),0,'Mute preference survives reload');assert.equal(await page.locator('.mh-intro-v118').evaluate(e=>e.scrollWidth>e.clientWidth),false);await page.screenshot({path:path.join(root,'outputs/music-intro-v118-phone.png')});await page.locator('[data-intro-skip]').click();await page.waitForSelector('.mh-intro-v118',{state:'detached'});
 await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:320,height:568});await start();assert.equal(await page.locator('.mh-intro-v118').evaluate(e=>e.scrollWidth>e.clientWidth),false);assert.equal(await page.locator('.mh-intro-v118').evaluate(e=>e.classList.contains('is-reduced')),true);await page.waitForSelector('.mh-intro-v118',{state:'detached',timeout:4000});
 assert.equal(await page.evaluate(()=>telechatMusicIntroV118.enter(document.querySelector('#music-hub-v117'),'already-playing',{track:{id:'fixture'},paused:false})),false,'Do not interrupt playing music');
 await start();await page.evaluate(()=>window.dispatchEvent(new CustomEvent('telechat-music-progress-v117',{detail:{track:{id:'fixture'},paused:false}})));await page.waitForSelector('.mh-intro-v118',{state:'detached'});assert.equal(await page.locator('.mh-nav').evaluate(e=>e.inert),false);
 await start();await page.evaluate(()=>telechatMusicHubV117.close());await page.waitForSelector('.mh-intro-v118',{state:'detached'});assert.equal(await page.locator('.mh-nav').evaluate(e=>e.inert),false,'Closing hub cleans up intro');
 assert.deepEqual(errors,[]);console.log('PASS intro: sound starts/closes, timed reveal, skip/Escape, mute persistence, once per session, 320/390 layouts, reduced motion, no playback interruption, cleanup.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
