/* Read-only lease filter check and isolated ephemeral Realtime channel test. */
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('playwright');const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const url=html.match(/const SUPABASE_URL='([^']+)'/)[1],key=html.match(/const SUPABASE_KEY='([^']+)'/)[1];
(async()=>{const response=await fetch(url+'/rest/v1/typing?select=ts&ts=eq.18000000000001&limit=0',{headers:{apikey:key,Authorization:'Bearer '+key}});assert.equal(response.status,200,'Public typing endpoint accepts numeric lease filter');assert.deepEqual(await response.json(),[]);
 const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage();await page.goto('https://dark178098345-star.github.io/-telechat/',{waitUntil:'domcontentloaded'});const result=await page.evaluate(async({url,key})=>{const client=supabase.createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),clientB=supabase.createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),topic='presence-v120-check-'+crypto.randomUUID(),a=client.channel(topic,{config:{presence:{key:'test-a'}}}),b=clientB.channel(topic,{config:{presence:{key:'test-b'}}});let synced=0;b.on('presence',{event:'sync'},()=>synced++);
 const subscribe=c=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Live presence connection timeout')),15000);c.subscribe(s=>{if(s==='SUBSCRIBED'){clearTimeout(timer);resolve();}if(s==='CHANNEL_ERROR'){clearTimeout(timer);reject(new Error(s));}});});
 const until=async fn=>{for(let i=0;i<50;i++){if(fn())return;await new Promise(r=>setTimeout(r,100));}throw Error('Presence event timeout');};
 try{await Promise.all([subscribe(a),subscribe(b)]);await a.track({nick:'fixture',state:'online'});await b.track({nick:'fixture',state:'background'});await until(()=>Object.keys(b.presenceState()).length===2);await a.untrack();await until(()=>Object.keys(b.presenceState()).length===1);return {synced,remaining:Object.keys(b.presenceState()).length};}finally{await Promise.all([client.removeAllChannels(),clientB.removeAllChannels()]);}
 },{url,key});assert.equal(result.remaining,1);assert.ok(result.synced>=2);console.log('PASS live Supabase: numeric lease filter, two isolated clients, presence sync and per-session untrack; no user rows changed.');}finally{await browser.close();}})().catch(e=>{console.error(e.message);process.exitCode=1});
