const assert=require('node:assert/strict'),m=require('../presence-model-v120.js');
const now=1800000000000;
const row=(id,state,age=0,device='pc')=>({nick:'alice',chat_key:m.PREFIX+id+':'+device,ts:m.encode(now-age,state)});
const reduce=(rows,extra={})=>m.reduce({rows,now,lastSeen:now,available:true,...extra});
assert.equal(reduce([row('a','background'),row('b','online',100,'phone')]).state,'online');
assert.equal(reduce([row('a','offline'),row('b','online',100,'phone')]).device,'phone');
assert.equal(reduce([row('a','background'),row('b','background')]).state,'background');
assert.equal(reduce([row('a','online',65001)]).state,'offline','Expired online lease must not fall back to fresh users.last_seen');
assert.equal(reduce([row('a','background',120001)]).state,'offline');
assert.equal(reduce([row('a','offline')]).state,'offline');
assert.equal(m.label(reduce([row('a','offline')]),now),'был(а) только что');
assert.equal(reduce([]).state,'online','Legacy fallback');
assert.equal(reduce([row('a','online',-90000)],{lastSeen:now+90000}).state,'offline','Future clock cannot mean online indefinitely');
const live={key:m.PREFIX+'a:pc',nick:'alice',state:'online',device:'pc',at:now-86400000};
assert.equal(reduce([row('a','online',90000)],{live:[live]}).state,'online','Connected unchanged presence stays valid');
assert.equal(reduce([row('a','background')],{live:[live]}).state,'background','Newer database state supersedes a delayed live state');
assert.equal(reduce([row('a','online',1000)],{departed:new Map([[live.key,{at:now,state:'online'}]])}).state,'offline','Confirmed disconnect overrides stale row');
assert.equal(reduce([row('a','background',1000)],{departed:new Map([[live.key,{at:now,state:'background'}]])}).state,'background','Suspended background uses a bounded grace period');
assert.equal(reduce([row('a','offline',1)],{departed:new Map([[live.key,{at:now,state:'background'}]])}).state,'offline','Explicit logout clears background grace');
assert.equal(reduce([row('a','online',70000)],{available:false}).state,'unknown','Network failure does not claim confirmed offline');
assert.equal(reduce([row('a','background'),{nick:'alice',chat_key:'__telechat_device_pc_v72__',ts:now-5000}]).state,'background','Old version device marker cannot override a newer state');
assert.equal(reduce([row('a','background'),{nick:'alice',chat_key:'__telechat_device_phone_v72__',ts:now-5000}]).state,'online','Old phone and new desktop still coexist');
assert.equal(reduce([row('a','online')],{reachable:false}).state,'unknown','Offline viewer must not show cached green online');
assert.equal(m.label({state:'unknown',lastSeen:now-300000},now),'был(а) 5 мин. назад','Preserve confirmed last seen on failed status fetch');
assert.equal(m.label({state:'unknown',lastSeen:0,reason:'loading'},now),'обновляем статус…');
assert.equal(m.label({state:'unknown',lastSeen:0,reason:'offline'},now),'нет соединения');
assert.equal(m.label({state:'unknown',lastSeen:0,reason:'unavailable'},now),'нет данных об активности');
assert.equal(reduce([],{lastSeen:now+90000,available:false}).lastSeen,0,'Invalid future fallback must not turn into just-seen');
console.log('PASS presence model: multidevice precedence, lease expiry, disconnects, clock bounds, old clients, honest last-seen labels.');
