const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const style=fs.readFileSync(path.join(root,'profile-follow-compact-v102.css'),'utf8');
const script=fs.readFileSync(path.join(root,'profile-follow-compact-v102.js'),'utf8');
const worker=fs.readFileSync(path.join(root,'sw.js'),'utf8');
assert.match(html,/profile-follow-compact-v102\.css\?v=102/);
assert.match(html,/profile-follow-compact-v102\.js\?v=102/);
assert.match(style,/profile-follow-compact-v102/);
assert.match(style,/height:min\(704px/);
assert.match(script,/follow-stats/);
assert.match(script,/follow-btn/);
assert.match(worker,/profile-follow-compact-v102\.css\?v=102/);
assert.match(worker,/profile-follow-compact-v102\.js\?v=102/);
console.log('profile-follow-compact-v102 smoke ok');
