const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const base='https://dark178098345-star.github.io/-telechat/';
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await browser.newPage({viewport:{width:1280,height:900}}),errors=[],requests=[];p.on('pageerror',e=>errors.push(e.message));
 await p.route('**/*',r=>{const url=new URL(r.request().url()),file=url.pathname.replace('/-telechat/','');requests.push(file);if(file.startsWith('vendor/qr/')&&fs.existsSync(path.join(root,file)))return r.fulfill({contentType:'text/javascript',body:read(file)});return r.fulfill({contentType:'text/html; charset=utf-8',body:'<!doctype html><meta charset="utf-8"><div id="auth-screen"></div><div id="chat-screen" class="active"><aside id="sidebar"><div class="sidebar-top"></div><nav class="section-rail-v109"></nav></aside></div>'});});
 async function boot(hash='',logged=true){await p.goto('about:blank');await p.goto(base+hash);const index=read('index.html');for(const m of index.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g))await p.addStyleTag({content:m[1]});for(const m of index.matchAll(/<link[^>]+href="\.\/([^"?]+\.css)(?:\?[^" ]*)?"/g))await p.addStyleTag({content:read(m[1])});await p.evaluate(logged=>{window.me=logged?{nick:'creator',name:'Creator'}:null;window.openedProfiles=[];window.toasts=[];window.showToast=s=>toasts.push(s);window.openUserProfile=async nick=>openedProfiles.push(nick);window.setAvatarElement=(el,u)=>el.textContent=u.name[0];if(!logged)document.querySelector('#chat-screen').classList.remove('active');},logged);await p.addScriptTag({content:read('qr-profile-v131.js')});}
 await boot();assert(!requests.some(s=>s.startsWith('vendor/qr/')),'QR libraries do not execute/load eagerly');
 assert.equal(await p.locator('.section-rail-v109 .qr-entry-v131').count(),1);await p.getByRole('button',{name:'Мой QR',exact:true}).click();await p.waitForFunction(()=>!document.querySelector('.qr-actions-v131 button').disabled);
 await p.addScriptTag({content:read('vendor/qr/jsqr-1.4.0.js')});
 assert.equal(await p.evaluate(()=>{const c=document.querySelector('.qr-code-v131 canvas'),d=c.getContext('2d').getImageData(0,0,c.width,c.height);return jsQR(d.data,d.width,d.height).data;}),base+'#profile=creator','actual generated QR decodes to profile link');
 assert.deepEqual(await p.evaluate(()=>['https://evil.test/-telechat/#profile=creator','javascript:alert(1)','https://dark178098345-star.github.io.evil.test/-telechat/#profile=creator','http://dark178098345-star.github.io/-telechat/#profile=creator','https://dark178098345-star.github.io/other/#profile=creator','https://dark178098345-star.github.io/-telechat/#profile=creator&profile=evil','https://user@dark178098345-star.github.io/-telechat/#profile=creator','https://dark178098345-star.github.io/-telechat/#profile=%3Cscript%3E'].map(telechatQrV131.parse)),Array(8).fill(null));
 const qrImage=Buffer.from((await p.locator('.qr-code-v131 canvas').evaluate(c=>c.toDataURL())).split(',')[1],'base64');
 const download= p.waitForEvent('download');await p.getByRole('button',{name:'Сохранить QR',exact:true}).click();const saved=await download;assert.equal(saved.suggestedFilename(),'telechat-creator-qr.png');
 await p.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('denied','NotAllowedError');};});await p.getByRole('button',{name:'Отсканировать',exact:true}).click();await p.getByRole('status').filter({hasText:'Камера не разрешена'}).waitFor();
 await p.locator('input[type=file]').setInputFiles({name:'qr.png',mimeType:'image/png',buffer:qrImage});await p.waitForFunction(()=>openedProfiles.length===1);assert.deepEqual(await p.evaluate(()=>openedProfiles),['creator']);assert.equal(await p.locator('.qr-overlay-v131').isVisible(),false);
 await p.locator('.qr-entry-v131').click();await p.waitForFunction(()=>!document.querySelector('.qr-actions-v131 button').disabled);await p.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{const source=document.querySelector('.qr-code-v131 canvas'),frame=document.createElement('canvas');frame.width=frame.height=640;const ctx=frame.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,640,640);ctx.drawImage(source,64,64,512,512);window.testCamera=frame.captureStream(2);return testCamera;};});await p.getByRole('button',{name:'Отсканировать',exact:true}).click();await p.waitForFunction(()=>openedProfiles.length===2);assert.equal(await p.evaluate(()=>testCamera.getTracks()[0].readyState),'ended','camera video frame decodes and successful scan releases the stream');
 await p.locator('.qr-entry-v131').click();await p.waitForFunction(()=>!document.querySelector('.qr-actions-v131 button').disabled);
 await p.evaluate(()=>{window.stopped=0;window.mediaResolve=null;navigator.mediaDevices.getUserMedia=opts=>{window.cameraOptions=opts;return new Promise(resolve=>window.mediaResolve=resolve);};});await p.getByRole('button',{name:'Отсканировать',exact:true}).click();await p.waitForFunction(()=>!!mediaResolve);await p.getByRole('button',{name:'Закрыть',exact:true}).click();await p.evaluate(()=>mediaResolve({getTracks:()=>[{stop:()=>stopped++}]}));await p.waitForFunction(()=>stopped===1);assert.equal(await p.evaluate(()=>cameraOptions.audio),false,'scanner does not request microphone');
 await p.locator('.qr-entry-v131').click();await p.waitForFunction(()=>!document.querySelector('.qr-actions-v131 button').disabled);await p.evaluate(()=>{HTMLMediaElement.prototype.play=async function(){};navigator.mediaDevices.getUserMedia=async()=>{const s=new MediaStream();s.getTracks=()=>[{stop:()=>stopped++}];return s;};});await p.getByRole('button',{name:'Отсканировать',exact:true}).click();await p.waitForFunction(()=>!!document.querySelector('video').srcObject);await p.evaluate(()=>window.dispatchEvent(new CustomEvent('telechat-native-visibility',{detail:{background:true}})));assert.equal(await p.evaluate(()=>document.querySelector('video').srcObject),null);assert.equal(await p.evaluate(()=>stopped),2);await p.evaluate(()=>window.dispatchEvent(new CustomEvent('telechat-native-visibility',{detail:{background:false}})));
 await p.getByRole('button',{name:'Мой QR',exact:true}).last().click();
 for(const width of [1280,390,320]){await p.setViewportSize({width,height:800});await p.waitForTimeout(80);const r=await p.locator('.qr-card-v131').boundingBox();assert(r.x>=0&&r.x+r.width<=width,'modal fits screen');const horizontal=await p.locator('.qr-card-v131').evaluate(el=>el.scrollWidth<=el.clientWidth);assert(horizontal,'no horizontal overflow');if(width<721)assert.equal(await p.locator('.sidebar-top .qr-entry-v131').count(),1);fs.mkdirSync(path.join(root,'outputs'),{recursive:true});await p.screenshot({path:path.join(root,'outputs',`qr-v131-${width}.png`)});}
 await p.keyboard.press('Escape');assert.equal(await p.locator('.qr-overlay-v131').isVisible(),false);
 await boot('#profile=friend',false);assert.deepEqual(await p.evaluate(()=>openedProfiles),[]);await p.evaluate(()=>{me={nick:'creator',name:'Creator'};document.querySelector('#chat-screen').classList.add('active');});await p.waitForFunction(()=>openedProfiles.length===1);assert.deepEqual(await p.evaluate(()=>openedProfiles),['friend']);assert.equal(new URL(p.url()).hash,'','consumed profile link is removed');
 await p.evaluate(()=>location.hash='profile=another');await p.waitForFunction(()=>openedProfiles.length===2);assert.deepEqual(await p.evaluate(()=>openedProfiles),['friend','another']);
 await p.locator('.qr-entry-v131').click();await p.waitForFunction(()=>!document.querySelector('.qr-actions-v131 button').disabled);await p.evaluate(()=>{me=null;document.querySelector('#chat-screen').classList.remove('active');});await p.waitForFunction(()=>document.querySelector('.qr-overlay-v131').hidden);assert.deepEqual(errors,[]);
 console.log('PASS QR: actual encode/decode, safe links, lazy libraries, PNG export, image scanner, permission denial, late camera cleanup, background cleanup, mobile/desktop layouts, focus/Escape, deferred login link, account logout');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
