const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage();await p.route('**/*',r=>r.fulfill({contentType:'text/html',body:'<div id="active-chat"><div id="messages"></div></div>'}));await p.goto('http://telechat.test');await p.addStyleTag({content:'#messages{height:400px;overflow:auto;overflow-anchor:none}.msg{height:80px}'+read('chat-scroll-v132.css')});await p.evaluate(()=>Object.assign(window,{
 me:{nick:'me'},currentChat:'friend',currentRoom:null,lastRenderedDate:'',userCache:{},serverRows:[],conversationKey:()=>currentChat?'me_'+currentChat:'',renderMessages:async()=>{},updateStatusBar:async()=>{},markAsRead:async()=>{},avatarMarkup:()=>'',renderPoll:()=>{},scrollToBottom:()=>{},batchUsersV15:async()=>{},isOnline:()=>false,formatLastSeen:()=>'',normalizedRoomVisibility:()=>'',makeDateStr:()=> 'today',
 sb:{from:table=>({select(){return this},eq(){return this},order(){return this},limit(n){this.count=n;return this},lt(f,v){this.before=v;return this},async then(resolve,reject){try{if(table==='messages'&&this.before&&window.delayOlder)await new Promise(r=>window.finishOlder=r);return resolve({data:table==='messages'?serverRows.filter(r=>!this.before||r.ts<this.before).sort((a,b)=>b.ts-a.ts).slice(0,this.count):[]});}catch(e){reject(e);}}})},
 appendMessage:async(m,scroll=true)=>{const row=document.createElement('div');row.className='msg';row.dataset.id=m.id||'';row.textContent=m.text;document.querySelector('#messages').append(row);if(scroll)scrollToBottom();},openChat:async()=>{await renderMessages();}
 }));for(const f of ['chat-speed-v51.js','chat-scroll-v132.js'])await p.addScriptTag({content:read(f)});
 await p.evaluate(async()=>{serverRows=Array.from({length:150},(_,i)=>({id:i+1,ts:i+1,chat_key:conversationKey(),from_nick:'friend',text:String(i+1)}));await openChat();});await p.waitForTimeout(80);
 const gap=()=>p.locator('#messages').evaluate(e=>e.scrollHeight-e.scrollTop-e.clientHeight);
 await p.locator('#messages').evaluate(e=>{e.dispatchEvent(new WheelEvent('wheel',{deltaY:-600}));e.scrollTop=600;});await p.waitForTimeout(50);
 await p.evaluate(()=>appendMessage({id:151,ts:151,chat_key:conversationKey(),from_nick:'friend',text:'incoming'}));await p.waitForTimeout(80);assert.equal(await p.locator('#messages').evaluate(e=>e.scrollTop),600,'incoming does not interrupt reading');
 await p.evaluate(()=>appendMessage({ts:152,chat_key:conversationKey(),from_nick:'me',text:'sent'}));await p.waitForTimeout(80);assert(await gap()<3,'own optimistic send reaches bottom');
 await p.locator('#messages').evaluate(e=>{e.dispatchEvent(new WheelEvent('wheel',{deltaY:-900}));e.scrollTop=20;});await p.waitForTimeout(40);await p.evaluate(()=>{window.delayOlder=true;window.historyTask=telechatChatSpeedV51.loadOlder();});await p.waitForFunction(()=>!!window.finishOlder);
 await p.locator('#messages').evaluate(e=>e.scrollTop=430);await p.waitForTimeout(30);const anchor=await p.evaluate(()=>{const box=document.querySelector('#messages'),r=[...box.querySelectorAll('.msg')].find(e=>e.getBoundingClientRect().bottom>box.getBoundingClientRect().top);return{id:r.dataset.id,top:r.getBoundingClientRect().top};});await p.evaluate(async()=>{finishOlder();await historyTask;});await p.waitForTimeout(80);const top=await p.locator('.msg[data-id="'+anchor.id+'"]').evaluate(e=>e.getBoundingClientRect().top);assert(Math.abs(top-anchor.top)<2,'history preserves current viewport rather than stale position before network');
 await p.evaluate(()=>appendMessage({id:153,ts:153,chat_key:conversationKey(),from_nick:'friend',text:'incoming again'}));await p.waitForTimeout(80);assert(Math.abs((await p.locator('.msg[data-id="'+anchor.id+'"]').evaluate(e=>e.getBoundingClientRect().top))-anchor.top)<2);await p.getByRole('button',{name:'К последним сообщениям'}).click();await p.waitForTimeout(60);assert(await gap()<3);
 console.log('PASS actual chat engine: own send scroll, incoming history preservation, wheel cancellation, delayed older-page viewport anchor, bottom button');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
