const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
async function fixture(browser){const p=await browser.newPage();await p.route('**/*',r=>r.abort());let html=read('index.html').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');html=html.replace(/<link\b[^>]*href="([^"?]+)[^"]*"[^>]*>/gi,(tag,file)=>file.endsWith('.css')?'<style>'+read(file)+'</style>':'');await p.setContent(html);await p.evaluate(()=>{document.getElementById('startup-loader')?.remove();document.getElementById('auth-screen')?.classList.remove('active');window.me={nick:'alice',name:'Алиса'};window.currentChat='bob';window.currentRoom=null;window.viewedProfileNickV5='bob';window.userCache={};window.showToast=()=>{};window.openUserProfile=async nick=>{viewedProfileNickV5=nick;document.getElementById('user-profile-modal').classList.add('show');};window.chatKey=(a,b)=>[a,b].sort().join('_');window.renderMessageContent=t=>t;window.messagePreviewText=t=>t;window.avatarMarkup=u=>u.name?.slice(0,1)||u.nick.slice(0,1);window.escHtml=t=>String(t).replace(/[<>&"]/g,'');window.unpackMedia=t=>{try{return JSON.parse(t);}catch(_){return null;}};});await p.addScriptTag({path:path.join(root,'ui-symbols-v125.js')});return p;}
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await fixture(browser),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.evaluate(()=>{
  window.queries=[];window.downloads=[];window.fail=false;window.delayed=false;window.sent=[];window.online=true;
  const img='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6WQAAAABJRU5ErkJggg==';
  window.messages=Array.from({length:40},(_,i)=>({id:100-i,ts:1000-i,chat_key:'alice_bob',deleted:false,from_nick:i%2?'alice':'bob',text:i===0?JSON.stringify({kind:'image',data:img}):i===1?JSON.stringify({kind:'file',data:JSON.stringify({name:'notes.txt',id:'file-id',size:120})}):i===2?'Ссылка https://example.com/path.':'hello'}));messages.push({id:50,ts:900,chat_key:'alice_bob',deleted:false,from_nick:'bob',text:'https://example.org/old'});messages.push({id:120,ts:2000,chat_key:'alice_eve',deleted:false,text:'https://private.test'});
  window.fixtureStory={id:'story-1',author_nick:'bob',media_url:'https://xvnazoervzccixtfhuaa.supabase.co/storage/v1/object/public/story-media/bob/story.jpg',media_type:'image',caption:'Вечер у моря',expires_at:Date.now()+600000};
  window.sb={from(table){const filters=[];let before=null,single=false,limit=40;const q={select(){return q;},eq(k,v){filters.push([k,v]);return q;},order(){return q;},limit(n){limit=n;return q;},or(v){before=v;return q;},maybeSingle(){single=true;return q;},abortSignal(){return q;},then(resolve){queries.push({table,filters,before});let data=table==='stories'?(fixtureStory?[fixtureStory]:[]):messages;data=data.filter(r=>filters.every(([k,v])=>r[k]===v));if(before)data=data.filter(r=>r.ts<Number(before.match(/ts.lt.(\d+)/)[1]));const result={data:single?data[0]||null:data.slice(0,limit),error:fail?{message:'offline'}:null};return new Promise(done=>{if(delayed)window.releaseQuery=()=>done(result);else done(result);}).then(resolve);}};return q;}};
  window.telechatAttachmentsV141={saveMessage:r=>downloads.push(r.id)};window.telechatDeliveryV72={sendDirect:async(nick,text,options)=>{sent.push({nick,text,options});return online;}};
 });
 for(const f of ['shared-media-v152.js','story-replies-v152.js'])await p.addScriptTag({path:path.join(root,f)});
 await p.evaluate(()=>openUserProfile('bob'));await p.locator('#shared-media-profile-v152').click();await p.waitForFunction(()=>document.querySelectorAll('.sm-photo-v152').length===1);assert.equal(await p.locator('.sm-photo-v152').count(),1);
 await p.locator('.sm-photo-v152').click();assert(await p.locator('#shared-media-preview-v152 img').isVisible());await p.getByRole('button',{name:'Сохранить фото',exact:true}).click();assert.deepEqual(await p.evaluate(()=>downloads),[100]);await p.getByRole('button',{name:'Назад к фото'}).click();
 await p.locator('[data-sm-tab="file"]').click();await p.locator('.sm-row-v152').click();assert.deepEqual(await p.evaluate(()=>downloads),[100,99]);await p.locator('[data-sm-tab="link"]').click();assert.equal(await p.locator('.sm-row-v152').getAttribute('href'),'https://example.com/path');await p.locator('#shared-media-more-v152').click();assert.equal(await p.locator('.sm-row-v152').count(),2);assert(!(await p.locator('#shared-media-more-v152').isVisible()));assert(await p.evaluate(()=>queries.filter(q=>q.table==='messages').every(q=>q.filters.some(([k,v])=>k==='chat_key'&&v==='alice_bob'))));
 for(const light of [false,true])for(const width of [320,390,1280]){await p.setViewportSize({width,height:800});await p.evaluate(x=>document.body.classList.toggle('theme-light',x),light);assert(await p.locator('#shared-media-v152').evaluate(e=>e.scrollWidth<=e.clientWidth));await p.screenshot({path:path.join(root,`outputs/shared-media-v152-${width}-${light}.png`)});}
 await p.keyboard.press('Escape');await p.evaluate(()=>{delayed=true;telechatSharedMediaV152.open('bob');});await p.waitForFunction(()=>!!releaseQuery);await p.evaluate(()=>{me={nick:'eve'};releaseQuery();});await p.waitForFunction(()=>!document.getElementById('shared-media-v152').open);await p.evaluate(()=>{me={nick:'alice'};delayed=false;document.getElementById('user-profile-modal').classList.remove('show');});
 // Mount in the real stories viewer; no writes to real users or hosted media.
 await p.addScriptTag({path:path.join(root,'stories-v115.js')});await p.evaluate(()=>{document.getElementById('story-viewer-v115').classList.add('open-v115');document.getElementById('story-stage-v115').style.minHeight='180px';telechatStoryRepliesV152.mount(fixtureStory);});
 const input=p.locator('#story-reply-form-v152 input');await input.fill('Красивое место!');await p.locator('#story-reply-form-v152 button').click();await p.waitForFunction(()=>sent.length===1);assert.equal(await p.evaluate(()=>sent[0].nick),'bob');assert.equal(await p.evaluate(()=>telechatStoryRepliesV152.parse(sent[0].text).text),'Красивое место!');assert((await p.locator('#story-reply-form-v152 p').textContent()).includes('Отправлено'));
 await p.evaluate(()=>{const box=document.createElement('div');box.id='reply-fixture';box.innerHTML=renderMessageContent(sent[0].text);document.body.append(box);});assert.equal(await p.locator('#reply-fixture .story-reply-reference-v152 img').count(),1);
 await p.evaluate(()=>{window.oldStory={...fixtureStory};fixtureStory=null;});await input.fill('Сохранить черновик');await p.locator('#story-reply-form-v152 button').click();await p.waitForFunction(()=>document.querySelector('#story-reply-form-v152 p').textContent.includes('недоступна'));assert.equal(await input.inputValue(),'Сохранить черновик');assert.equal(await p.evaluate(()=>sent.length),1);
 await p.evaluate(()=>{fixtureStory=oldStory;telechatStoryRepliesV152.mount({...oldStory,author_nick:'alice'});});assert(!(await p.locator('#story-reply-form-v152').isVisible()));
 await p.evaluate(()=>{telechatStoryRepliesV152.mount(oldStory);online=false;});await input.fill('<img src=x onerror=alert(1)>');await p.locator('#story-reply-form-v152 button').click();await p.waitForFunction(()=>sent.length===2);assert((await p.locator('#story-reply-form-v152 p').textContent()).includes('очереди'));
 await p.evaluate(()=>{document.getElementById('reply-fixture').innerHTML=renderMessageContent(sent[1].text);});assert.equal(await p.locator('.story-reply-text-v152 img').count(),0);
 for(const width of [320,390,1280]){await p.setViewportSize({width,height:740});assert(await p.locator('#story-reply-form-v152').evaluate(e=>{const r=e.getBoundingClientRect();return r.width>100&&r.right<=innerWidth&&r.bottom<=innerHeight;}));}
 assert.deepEqual(errors,[]);console.log('PASS shared media: scoped paginated queries, photo preview/save, file save, links, account switch, dark/light mobile/desktop. Story replies: recipient, preview, own/expired protection, queued delivery and safe text.');
 await p.close();
 const call=await fixture(browser);await call.evaluate(()=>{me=null;window.doLogin=async()=>{};window.openChat=async()=>{};window.openRoom=async()=>{};window.goBack=()=>{};window.getUser=async nick=>({nick,name:nick==='bob'?'Максим':nick,av:0});window.renderMessages=async()=>{};window.renderContacts=async()=>{};});for(const f of ['voice-calls-v32.js','call-chat-v152.js'])await call.addScriptTag({path:path.join(root,f)});await call.evaluate(()=>{me={nick:'alice',name:'Алиса'};return telechatCallsV32.preview('active','bob');});
 for(const width of [320,390,1280]){await call.setViewportSize({width,height:800});await call.locator('#call-chat-btn-v152').click();assert(await call.locator('#call-chat-panel-v152').isVisible());const input=call.locator('#call-chat-panel-v152 input');await input.fill('Тест');await call.locator('#call-chat-panel-v152 form button').click();assert((await call.locator('.call-chat-result-v152').textContent()).includes('предпросмотре'));await call.locator('#call-chat-panel-v152 header button').click();const bounds=await call.locator('.voice-call-controls').boundingBox();assert(bounds.x>=0&&bounds.x+bounds.width<=width+1);assert.equal(await call.locator('#call-mic-btn svg').count(),1);assert.equal(await call.locator('.voice-call-avatar').first().evaluate(e=>getComputedStyle(e).animationName),'none');await call.screenshot({path:path.join(root,`outputs/call-design-v152-${width}.png`)});}
 await call.evaluate(()=>minimizeCallV32());assert(await call.locator('#voice-call-mini').isVisible());await call.evaluate(()=>restoreCallV32());assert(await call.locator('#voice-call-overlay').isVisible());await call.evaluate(()=>telechatCallsV32.closePreview());await call.close();
 console.log('PASS call design: real renderer preview, 320/390/1280 controls, SVG icons, no avatar animation, chat toggle/error, minimize/restore/cleanup');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
