const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
async function fixture(browser){const page=await browser.newPage();await page.route('https://voice.test/**',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><button id="record-btn"></button><span id="recording-status"><span id="recording-time"></span></span><input id="chat-photo-input" type="file"><div id="messages"></div><div id="pending-media"></div>'}));await page.goto('https://voice.test');
 await page.evaluate(()=>{window.me={nick:'a'};window.key='a_b';window.pendingMedia=null;window.mediaRecorderV3=null;window.voiceStreamV3=null;window.sent=[];window.toasts=[];window.requests=0;window.streams=[];window.clock=1000;window.permissionGate=false;window.rejectPermission=false;window.empty=false;window.failRead=false;window.rejectConstructor=false;window.recorders=[];
 Object.defineProperty(performance,'now',{value:()=>clock});window.conversationKey=()=>key;window.canWriteCurrent=()=>true;window.showToast=t=>toasts.push(t);window.formatDuration=s=>'0:'+String(Math.round(s||0)).padStart(2,'0');window.escHtml=s=>String(s).replaceAll('"','&quot;');window.unpackMedia=t=>typeof t==='object'?t:null;window.renderMessageContent=t=>String(t);window.renderPendingMedia=()=>{};
 window.cancelPendingMedia=()=>pendingMedia=null;window.sendMsg=async()=>{sent.push({key,media:pendingMedia});cancelPendingMedia();};window.toggleVoiceRecording=()=>{};window.toggleVoicePlayback=()=>{};
 window.blobToDataUrl=async b=>{if(failRead)throw Error('read failed');return 'data:'+b.type+';base64,AAAA';};
 class Track extends EventTarget{constructor(){super();this.stopped=false;}stop(){this.stopped=true;}}
 navigator.mediaDevices.getUserMedia=async()=>{requests++;if(permissionGate)await new Promise(resolve=>window.grant=resolve);if(rejectPermission)throw new DOMException('denied','NotAllowedError');const track=new Track(),stream={getTracks:()=>[track],getAudioTracks:()=>[track]};streams.push(stream);return stream;};
 window.MediaRecorder=class extends EventTarget{static isTypeSupported(t){return t.includes('webm');}constructor(stream,options){super();if(rejectConstructor)throw Error('unsupported');this.state='inactive';this.mimeType=options.mimeType||'audio/webm';recorders.push(this);}start(){this.state='recording';}stop(){if(this.state==='inactive')throw Error('already stopped');this.state='inactive';setTimeout(()=>{this.ondataavailable?.({data:new Blob(empty?[]:['audio-bytes'],{type:this.mimeType})});this.onstop?.();this.dispatchEvent(new Event('stop'));},20);}};
 });for(const file of ['ui-symbols-v125.js','voice-send-v38.js'])await page.addScriptTag({content:read(file)});return page;}
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await fixture(browser),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.evaluate(()=>{permissionGate=true;window.starting=toggleVoiceRecording();toggleVoiceRecording();});assert.equal(await p.evaluate(()=>requests),1,'one microphone request');
 await p.evaluate(async()=>{cancelPendingMedia();grant();await starting;});assert.equal(await p.evaluate(()=>streams[0].getTracks()[0].stopped),true);assert.equal(await p.evaluate(()=>pendingMedia),null);
 await p.evaluate(async()=>{permissionGate=false;await toggleVoiceRecording();clock+=2000;window.stopping=toggleVoiceRecording();window.sending=sendMsg();sendMsg();});await p.evaluate(()=>Promise.all([stopping,sending]));
 assert.equal(await p.evaluate(()=>sent.length),1,'stop/send double click sends exactly once');assert.equal(await p.evaluate(()=>sent[0].media.duration),2);assert.equal(await p.evaluate(()=>telechatVoiceV125.getState()),'idle');
 await p.evaluate(async()=>{await toggleVoiceRecording();clock+=1000;window.sending2=sendMsg();key='a_c';cancelPendingMedia();await sending2;});assert.equal(await p.evaluate(()=>sent.length),1,'chat switch must not send into new chat');
 await p.evaluate(async()=>{rejectPermission=true;await toggleVoiceRecording();rejectPermission=false;});assert.match(await p.evaluate(()=>toasts.at(-1)),/доступ/);assert.equal(await p.evaluate(()=>telechatVoiceV125.getState()),'idle');
 await p.evaluate(async()=>{rejectConstructor=true;await toggleVoiceRecording();rejectConstructor=false;});assert.equal(await p.evaluate(()=>streams.at(-1).getTracks()[0].stopped),true);
 await p.evaluate(async()=>{empty=true;await toggleVoiceRecording();clock+=1000;await toggleVoiceRecording();empty=false;});assert.equal(await p.evaluate(()=>pendingMedia),null);
 await p.evaluate(async()=>{failRead=true;await toggleVoiceRecording();clock+=1000;await toggleVoiceRecording();failRead=false;});assert.equal(await p.evaluate(()=>telechatVoiceV125.getState()),'idle');
 await p.evaluate(async()=>{await toggleVoiceRecording();clock+=1000;dispatchEvent(new CustomEvent('telechat-native-visibility',{detail:{background:true}}));});await p.waitForFunction(()=>telechatVoiceV125.getState()==='idle');assert.equal(await p.evaluate(()=>pendingMedia.kind),'voice');assert.equal(await p.evaluate(()=>sent.length),1,'background saves draft, never auto sends');
 await p.evaluate(()=>{cancelPendingMedia();dispatchEvent(new CustomEvent('telechat-native-visibility',{detail:{background:false}}));});
 await p.evaluate(async()=>{permissionGate=true;window.late=toggleVoiceRecording();dispatchEvent(new CustomEvent('telechat-native-visibility',{detail:{background:true}}));dispatchEvent(new CustomEvent('telechat-native-visibility',{detail:{background:false}}));grant();await late;clock+=1000;});assert.equal(await p.evaluate(()=>telechatVoiceV125.getState()),'recording','permission overlay resume allows recording');await p.evaluate(()=>telechatVoiceV125.cancel());
 assert(await p.evaluate(()=>streams.every(s=>s.getTracks()[0].stopped)),'all microphone tracks released');assert.deepEqual(errors,[]);
 assert(await p.evaluate(()=>renderMessageContent({kind:'voice',data:'data:audio/webm;base64,AAAA" onerror="alert(1)',duration:1}).includes('повреждено')),'unsafe legacy media is rejected');
 console.log('PASS voice: concurrent permissions, late grants, stop/send race, chat change, permission/codec/read failures, empty audio, background draft, native permission overlay, microphone cleanup');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
